twolooptadpolediags={
{ToSSS,{
{{{Ah, i1, 4}, {Ah, i2, 4}, {hh, i3, 4}},{{1/2,TfSSS,{0, 0}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}, {hh, i3}}, C[Ah, Ah, hh, hh]}, {{{Ah, i1}, {Ah, i2}, {hh, i3}}, C[Ah, Ah, hh]}}},
{{{Ah, i1, 4}, {Hpm, i2, 4}, {conj[Hpm], i3, 4}},{{1,TfSSS,{0, 0}}},{{{{Ah, i1}, {hh, gE1}, {Hpm, i2}, {conj[Hpm], i3}}, C[Ah, hh, Hpm, conj[Hpm]]}, {{{Ah, i1}, {Hpm, i3}, {conj[Hpm], i2}}, C[Ah, Hpm, conj[Hpm]]}}},
{{{Ah, i1, 4}, {Hppmm, i2, 2}, {conj[Hppmm], i3, 2}},{{1,TfSSS,{0, 0}}},{{{{Ah, i1}, {hh, gE1}, {Hppmm, i2}, {conj[Hppmm], i3}}, C[Ah, hh, Hppmm, conj[Hppmm]]}, {{{Ah, i1}, {Hppmm, i3}, {conj[Hppmm], i2}}, C[Ah, Hppmm, conj[Hppmm]]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {hh, i3, 4}},{{1/6,TfSSS,{0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}, {hh, i3}}, C[hh, hh, hh, hh]}, {{{hh, i1}, {hh, i2}, {hh, i3}}, C[hh, hh, hh]}}},
{{{hh, i1, 4}, {Hpm, i2, 4}, {conj[Hpm], i3, 4}},{{1,TfSSS,{0, 0}}},{{{{hh, gE1}, {hh, i1}, {Hpm, i2}, {conj[Hpm], i3}}, C[hh, hh, Hpm, conj[Hpm]]}, {{{hh, i1}, {Hpm, i3}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}}},
{{{hh, i1, 4}, {Hppmm, i2, 2}, {conj[Hppmm], i3, 2}},{{1,TfSSS,{0, 0}}},{{{{hh, gE1}, {hh, i1}, {Hppmm, i2}, {conj[Hppmm], i3}}, C[hh, hh, Hppmm, conj[Hppmm]]}, {{{hh, i1}, {Hppmm, i3}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}}},
{{{Hpm, i1, 4}, {Hpm, i2, 4}, {conj[Hppmm], i3, 2}},{{1,TfSSS,{0, 0}}},{{{{hh, gE1}, {Hpm, i1}, {Hpm, i2}, {conj[Hppmm], i3}}, C[hh, Hpm, Hpm, conj[Hppmm]]}, {{{Hppmm, i3}, {conj[Hpm], i1}, {conj[Hpm], i2}}, C[Hppmm, conj[Hpm], conj[Hpm]]}}}
}},
{ToSS,{
{{{Ah, i1, 4}, {Ah, i2, 4}, {Ah, i3, 4}},{{1/4,TfSS,{0, 0}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i2}, {Ah, i3}, {Ah, i3}}, C[Ah, Ah, Ah, Ah]}}},
{{{Ah, i1, 4}, {Ah, i2, 4}, {hh, i3, 4}},{{1/4,TfSS,{0, 0}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i2}, {hh, i3}, {hh, i3}}, C[Ah, Ah, hh, hh]}}},
{{{Ah, i1, 4}, {Ah, i2, 4}, {Hpm, i3, 4}},{{1/2,TfSS,{0, 0}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i2}, {Hpm, i3}, {conj[Hpm], i3}}, C[Ah, Ah, Hpm, conj[Hpm]]}}},
{{{Ah, i1, 4}, {Ah, i2, 4}, {Hppmm, i3, 2}},{{1/2,TfSS,{0, 0}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i2}, {Hppmm, i3}, {conj[Hppmm], i3}}, C[Ah, Ah, Hppmm, conj[Hppmm]]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Ah, i3, 4}},{{1/4,TfSS,{0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{Ah, i3}, {Ah, i3}, {hh, i1}, {hh, i2}}, C[Ah, Ah, hh, hh]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {hh, i3, 4}},{{1/4,TfSS,{0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{hh, i1}, {hh, i2}, {hh, i3}, {hh, i3}}, C[hh, hh, hh, hh]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Hpm, i3, 4}},{{1/2,TfSS,{0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{hh, i1}, {hh, i2}, {Hpm, i3}, {conj[Hpm], i3}}, C[hh, hh, Hpm, conj[Hpm]]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Hppmm, i3, 2}},{{1/2,TfSS,{0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{hh, i1}, {hh, i2}, {Hppmm, i3}, {conj[Hppmm], i3}}, C[hh, hh, Hppmm, conj[Hppmm]]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {Ah, i3, 4}},{{1/2,TfSS,{0, 0}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{Ah, i3}, {Ah, i3}, {Hpm, i2}, {conj[Hpm], i1}}, C[Ah, Ah, Hpm, conj[Hpm]]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {hh, i3, 4}},{{1/2,TfSS,{0, 0}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{hh, i3}, {hh, i3}, {Hpm, i2}, {conj[Hpm], i1}}, C[hh, hh, Hpm, conj[Hpm]]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {Hpm, i3, 4}},{{1,TfSS,{0, 0}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{Hpm, i2}, {Hpm, i3}, {conj[Hpm], i1}, {conj[Hpm], i3}}, C[Hpm, Hpm, conj[Hpm], conj[Hpm]]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {Hppmm, i3, 2}},{{1,TfSS,{0, 0}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{Hpm, i2}, {Hppmm, i3}, {conj[Hpm], i1}, {conj[Hppmm], i3}}, C[Hpm, Hppmm, conj[Hpm], conj[Hppmm]]}}},
{{{Hppmm, i1, 2}, {conj[Hppmm], i2, 2}, {Ah, i3, 4}},{{1/2,TfSS,{0, 0}}},{{{{hh, gE1}, {Hppmm, i1}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}, {{{Ah, i3}, {Ah, i3}, {Hppmm, i2}, {conj[Hppmm], i1}}, C[Ah, Ah, Hppmm, conj[Hppmm]]}}},
{{{Hppmm, i1, 2}, {conj[Hppmm], i2, 2}, {hh, i3, 4}},{{1/2,TfSS,{0, 0}}},{{{{hh, gE1}, {Hppmm, i1}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}, {{{hh, i3}, {hh, i3}, {Hppmm, i2}, {conj[Hppmm], i1}}, C[hh, hh, Hppmm, conj[Hppmm]]}}},
{{{Hppmm, i1, 2}, {conj[Hppmm], i2, 2}, {Hpm, i3, 4}},{{1,TfSS,{0, 0}}},{{{{hh, gE1}, {Hppmm, i1}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}, {{{Hpm, i3}, {Hppmm, i2}, {conj[Hpm], i3}, {conj[Hppmm], i1}}, C[Hpm, Hppmm, conj[Hpm], conj[Hppmm]]}}},
{{{Hppmm, i1, 2}, {conj[Hppmm], i2, 2}, {Hppmm, i3, 2}},{{1,TfSS,{0, 0}}},{{{{hh, gE1}, {Hppmm, i1}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}, {{{Hppmm, i2}, {Hppmm, i3}, {conj[Hppmm], i1}, {conj[Hppmm], i3}}, C[Hppmm, Hppmm, conj[Hppmm], conj[Hppmm]]}}}
}},
{ToSSSS,{
{{{Ah, i1, 4}, {Ah, i2, 4}, {Ah, i3, 4}, {hh, i4, 4}},{{-1/2,TfSSSS,{0, 0, 0}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Ah, i3}, {hh, i4}}, C[Ah, Ah, hh]}, {{{Ah, i2}, {Ah, i3}, {hh, i4}}, C[Ah, Ah, hh]}}},
{{{Ah, i1, 4}, {Ah, i2, 4}, {Hpm, i3, 4}, {conj[Hpm], i4, 4}},{{-1/2,TfSSSS,{0, 0, 0}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Hpm, i3}, {conj[Hpm], i4}}, C[Ah, Hpm, conj[Hpm]]}, {{{Ah, i2}, {Hpm, i4}, {conj[Hpm], i3}}, C[Ah, Hpm, conj[Hpm]]}}},
{{{Ah, i1, 4}, {Ah, i2, 4}, {Hppmm, i3, 2}, {conj[Hppmm], i4, 2}},{{-1/2,TfSSSS,{0, 0, 0}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{Ah, i1}, {Hppmm, i3}, {conj[Hppmm], i4}}, C[Ah, Hppmm, conj[Hppmm]]}, {{{Ah, i2}, {Hppmm, i4}, {conj[Hppmm], i3}}, C[Ah, Hppmm, conj[Hppmm]]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Ah, i3, 4}, {Ah, i4, 4}},{{-1/4,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{Ah, i3}, {Ah, i4}, {hh, i1}}, C[Ah, Ah, hh]}, {{{Ah, i3}, {Ah, i4}, {hh, i2}}, C[Ah, Ah, hh]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {hh, i3, 4}, {hh, i4, 4}},{{-1/4,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{hh, i1}, {hh, i3}, {hh, i4}}, C[hh, hh, hh]}, {{{hh, i2}, {hh, i3}, {hh, i4}}, C[hh, hh, hh]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Hpm, i3, 4}, {conj[Hpm], i4, 4}},{{-1/2,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{hh, i1}, {Hpm, i3}, {conj[Hpm], i4}}, C[hh, Hpm, conj[Hpm]]}, {{{hh, i2}, {Hpm, i4}, {conj[Hpm], i3}}, C[hh, Hpm, conj[Hpm]]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Hppmm, i3, 2}, {conj[Hppmm], i4, 2}},{{-1/2,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{hh, i1}, {Hppmm, i3}, {conj[Hppmm], i4}}, C[hh, Hppmm, conj[Hppmm]]}, {{{hh, i2}, {Hppmm, i4}, {conj[Hppmm], i3}}, C[hh, Hppmm, conj[Hppmm]]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {Ah, i3, 4}, {Hpm, i4, 4}},{{-1,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{Ah, i3}, {Hpm, i4}, {conj[Hpm], i1}}, C[Ah, Hpm, conj[Hpm]]}, {{{Ah, i3}, {Hpm, i2}, {conj[Hpm], i4}}, C[Ah, Hpm, conj[Hpm]]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {hh, i3, 4}, {Hpm, i4, 4}},{{-1,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{hh, i3}, {Hpm, i4}, {conj[Hpm], i1}}, C[hh, Hpm, conj[Hpm]]}, {{{hh, i3}, {Hpm, i2}, {conj[Hpm], i4}}, C[hh, Hpm, conj[Hpm]]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {Hppmm, i3, 2}, {conj[Hpm], i4, 4}},{{-1,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{Hppmm, i3}, {conj[Hpm], i1}, {conj[Hpm], i4}}, C[Hppmm, conj[Hpm], conj[Hpm]]}, {{{Hpm, i2}, {Hpm, i4}, {conj[Hppmm], i3}}, C[Hpm, Hpm, conj[Hppmm]]}}},
{{{Hppmm, i1, 2}, {conj[Hppmm], i2, 2}, {Ah, i3, 4}, {Hppmm, i4, 2}},{{-1,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {Hppmm, i1}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}, {{{Ah, i3}, {Hppmm, i4}, {conj[Hppmm], i1}}, C[Ah, Hppmm, conj[Hppmm]]}, {{{Ah, i3}, {Hppmm, i2}, {conj[Hppmm], i4}}, C[Ah, Hppmm, conj[Hppmm]]}}},
{{{Hppmm, i1, 2}, {conj[Hppmm], i2, 2}, {hh, i3, 4}, {Hppmm, i4, 2}},{{-1,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {Hppmm, i1}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}, {{{hh, i3}, {Hppmm, i4}, {conj[Hppmm], i1}}, C[hh, Hppmm, conj[Hppmm]]}, {{{hh, i3}, {Hppmm, i2}, {conj[Hppmm], i4}}, C[hh, Hppmm, conj[Hppmm]]}}},
{{{Hppmm, i1, 2}, {conj[Hppmm], i2, 2}, {Hpm, i3, 4}, {Hpm, i4, 4}},{{-1/2,TfSSSS,{0, 0, 0}}},{{{{hh, gE1}, {Hppmm, i1}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}, {{{Hpm, i3}, {Hpm, i4}, {conj[Hppmm], i1}}, C[Hpm, Hpm, conj[Hppmm]]}, {{{Hppmm, i2}, {conj[Hpm], i3}, {conj[Hpm], i4}}, C[Hppmm, conj[Hpm], conj[Hpm]]}}}
}},
{ToSSFF,{
{{{Ah, i1, 4}, {Ah, i2, 4}, {Fd, i3, 3}, {bar[Fd], i4, 3}},{{-3/2,TfSSFF,{0, L, R}},{3*Mass[Fd,i3]*Mass[bar[Fd],i4],TfSSFbFb,{0, L, L}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{bar[Fd], i4}, {Fd, i3}, {Ah, i1}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}, {Ah, i2}}, C[Ah, Fd, bar[Fd]]}}},
{{{Ah, i1, 4}, {Ah, i2, 4}, {Fe, i3, 3}, {bar[Fe], i4, 3}},{{-1/2,TfSSFF,{0, L, R}},{1*Mass[Fe,i3]*Mass[bar[Fe],i4],TfSSFbFb,{0, L, L}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{bar[Fe], i4}, {Fe, i3}, {Ah, i1}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}, {Ah, i2}}, C[Ah, Fe, bar[Fe]]}}},
{{{Ah, i1, 4}, {Ah, i2, 4}, {Fu, i3, 3}, {bar[Fu], i4, 3}},{{-3/2,TfSSFF,{0, L, R}},{3*Mass[Fu,i3]*Mass[bar[Fu],i4],TfSSFbFb,{0, L, L}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{bar[Fu], i4}, {Fu, i3}, {Ah, i1}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}, {Ah, i2}}, C[Ah, Fu, bar[Fu]]}}},
{{{Ah, i1, 4}, {Ah, i2, 4}, {Fv, i3, 6}, {Fv, i4, 6}},{{-1/4,TfSSFF,{0, L, R}},{1/2*Mass[Fv,i3]*Mass[Fv,i4],TfSSFbFb,{0, L, L}}},{{{{Ah, i1}, {Ah, i2}, {hh, gE1}}, C[Ah, Ah, hh]}, {{{Fv, i3}, {Fv, i4}, {Ah, i1}}, C[Ah, Fv, Fv]}, {{{Fv, i3}, {Fv, i4}, {Ah, i2}}, C[Ah, Fv, Fv]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Fd, i3, 3}, {bar[Fd], i4, 3}},{{-3/2,TfSSFF,{0, L, R}},{3*Mass[Fd,i3]*Mass[bar[Fd],i4],TfSSFbFb,{0, L, L}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{bar[Fd], i4}, {Fd, i3}, {hh, i1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i4}, {hh, i2}}, C[Fd, hh, bar[Fd]]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Fe, i3, 3}, {bar[Fe], i4, 3}},{{-1/2,TfSSFF,{0, L, R}},{1*Mass[Fe,i3]*Mass[bar[Fe],i4],TfSSFbFb,{0, L, L}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{bar[Fe], i4}, {Fe, i3}, {hh, i1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i4}, {hh, i2}}, C[Fe, hh, bar[Fe]]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Fu, i3, 3}, {bar[Fu], i4, 3}},{{-3/2,TfSSFF,{0, L, R}},{3*Mass[Fu,i3]*Mass[bar[Fu],i4],TfSSFbFb,{0, L, L}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{bar[Fu], i4}, {Fu, i3}, {hh, i1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i4}, {hh, i2}}, C[Fu, hh, bar[Fu]]}}},
{{{hh, i1, 4}, {hh, i2, 4}, {Fv, i3, 6}, {Fv, i4, 6}},{{-1/4,TfSSFF,{0, L, R}},{1/2*Mass[Fv,i3]*Mass[Fv,i4],TfSSFbFb,{0, L, L}}},{{{{hh, gE1}, {hh, i1}, {hh, i2}}, C[hh, hh, hh]}, {{{Fv, i3}, {Fv, i4}, {hh, i1}}, C[Fv, Fv, hh]}, {{{Fv, i3}, {Fv, i4}, {hh, i2}}, C[Fv, Fv, hh]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {Fd, i3, 3}, {bar[Fu], i4, 3}},{{-3,TfSSFF,{0, L, R}},{6*Mass[Fd,i3]*Mass[bar[Fu],i4],TfSSFbFb,{0, L, L}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{bar[Fu], i4}, {Fd, i3}, {conj[Hpm], i1}}, C[Fd, bar[Fu], conj[Hpm]]}, {{{bar[Fd], i3}, {Fu, i4}, {Hpm, i2}}, C[Fu, Hpm, bar[Fd]]}}},
{{{Hpm, i1, 4}, {conj[Hpm], i2, 4}, {Fe, i3, 3}, {Fv, i4, 6}},{{-1,TfSSFF,{0, L, R}},{2*Mass[Fe,i3]*Mass[Fv,i4],TfSSFbFb,{0, L, L}}},{{{{hh, gE1}, {Hpm, i1}, {conj[Hpm], i2}}, C[hh, Hpm, conj[Hpm]]}, {{{Fv, i4}, {Fe, i3}, {conj[Hpm], i1}}, C[Fe, Fv, conj[Hpm]]}, {{{bar[Fe], i3}, {Fv, i4}, {Hpm, i2}}, C[Fv, Hpm, bar[Fe]]}}},
{{{Hppmm, i1, 2}, {conj[Hppmm], i2, 2}, {Fe, i3, 3}, {Fe, i4, 3}},{{-1/2,TfSSFF,{0, L, R}},{1*Mass[Fe,i3]*Mass[Fe,i4],TfSSFbFb,{0, L, L}}},{{{{hh, gE1}, {Hppmm, i1}, {conj[Hppmm], i2}}, C[hh, Hppmm, conj[Hppmm]]}, {{{Fe, i3}, {Fe, i4}, {conj[Hppmm], i1}}, C[Fe, Fe, conj[Hppmm]]}, {{{bar[Fe], i3}, {bar[Fe], i4}, {Hppmm, i2}}, C[Hppmm, bar[Fe], bar[Fe]]}}}
}},
{ToFFFS,{
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fd, i3, 3}, {Ah, i4, 4}},{{-6*Mass[Fd,i3],TfFFFbS,{L, R, R}},{-6*Mass[bar[Fd],i2],TfFFbFS,{L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fd,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fd], i2}, {Fd, i1}, {hh, gE1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i3}, {Ah, i4}}, C[Ah, Fd, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i2}, {Ah, i4}}, C[Ah, Fd, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fd, i3, 3}, {hh, i4, 4}},{{-6*Mass[Fd,i3],TfFFFbS,{L, R, R}},{-6*Mass[bar[Fd],i2],TfFFbFS,{L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fd,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fd], i2}, {Fd, i1}, {hh, gE1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fd, i3}, {hh, i4}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i3}, {Fd, i2}, {hh, i4}}, C[Fd, hh, bar[Fd]]}}},
{{{Fd, i1, 3}, {bar[Fd], i2, 3}, {Fu, i3, 3}, {Hpm, i4, 4}},{{-6*Mass[Fu,i3],TfFFFbS,{L, R, R}},{-6*Mass[bar[Fd],i2],TfFFbFS,{L, R, L}},{6*Mass[Fd,i1]*Mass[bar[Fd],i2]*Mass[Fu,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fd], i2}, {Fd, i1}, {hh, gE1}}, C[Fd, hh, bar[Fd]]}, {{{bar[Fd], i1}, {Fu, i3}, {Hpm, i4}}, C[Fu, Hpm, bar[Fd]]}, {{{bar[Fu], i3}, {Fd, i2}, {conj[Hpm], i4}}, C[Fd, bar[Fu], conj[Hpm]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fe, i3, 3}, {Ah, i4, 4}},{{-2*Mass[Fe,i3],TfFFFbS,{L, R, R}},{-2*Mass[bar[Fe],i2],TfFFbFS,{L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fe,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fe], i2}, {Fe, i1}, {hh, gE1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i3}, {Ah, i4}}, C[Ah, Fe, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i2}, {Ah, i4}}, C[Ah, Fe, bar[Fe]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fe, i3, 3}, {hh, i4, 4}},{{-2*Mass[Fe,i3],TfFFFbS,{L, R, R}},{-2*Mass[bar[Fe],i2],TfFFbFS,{L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fe,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fe], i2}, {Fe, i1}, {hh, gE1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {Fe, i3}, {hh, i4}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i3}, {Fe, i2}, {hh, i4}}, C[Fe, hh, bar[Fe]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {Fv, i3, 6}, {Hpm, i4, 4}},{{-2*Mass[Fv,i3],TfFFFbS,{L, R, R}},{-2*Mass[bar[Fe],i2],TfFFbFS,{L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[Fv,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fe], i2}, {Fe, i1}, {hh, gE1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {Fv, i3}, {Hpm, i4}}, C[Fv, Hpm, bar[Fe]]}, {{{Fv, i3}, {Fe, i2}, {conj[Hpm], i4}}, C[Fe, Fv, conj[Hpm]]}}},
{{{Fe, i1, 3}, {bar[Fe], i2, 3}, {bar[Fe], i3, 3}, {Hppmm, i4, 2}},{{-2*Mass[bar[Fe],i3],TfFFFbS,{L, R, R}},{-2*Mass[bar[Fe],i2],TfFFbFS,{L, R, L}},{2*Mass[Fe,i1]*Mass[bar[Fe],i2]*Mass[bar[Fe],i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fe], i2}, {Fe, i1}, {hh, gE1}}, C[Fe, hh, bar[Fe]]}, {{{bar[Fe], i1}, {bar[Fe], i3}, {Hppmm, i4}}, C[Hppmm, bar[Fe], bar[Fe]]}, {{{Fe, i2}, {Fe, i3}, {conj[Hppmm], i4}}, C[Fe, Fe, conj[Hppmm]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fu, i3, 3}, {Ah, i4, 4}},{{-6*Mass[Fu,i3],TfFFFbS,{L, R, R}},{-6*Mass[bar[Fu],i2],TfFFbFS,{L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fu,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fu], i2}, {Fu, i1}, {hh, gE1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i3}, {Ah, i4}}, C[Ah, Fu, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i2}, {Ah, i4}}, C[Ah, Fu, bar[Fu]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fd, i3, 3}, {conj[Hpm], i4, 4}},{{-6*Mass[Fd,i3],TfFFFbS,{L, R, R}},{-6*Mass[bar[Fu],i2],TfFFbFS,{L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fd,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fu], i2}, {Fu, i1}, {hh, gE1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fd, i3}, {conj[Hpm], i4}}, C[Fd, bar[Fu], conj[Hpm]]}, {{{bar[Fd], i3}, {Fu, i2}, {Hpm, i4}}, C[Fu, Hpm, bar[Fd]]}}},
{{{Fu, i1, 3}, {bar[Fu], i2, 3}, {Fu, i3, 3}, {hh, i4, 4}},{{-6*Mass[Fu,i3],TfFFFbS,{L, R, R}},{-6*Mass[bar[Fu],i2],TfFFbFS,{L, R, L}},{6*Mass[Fu,i1]*Mass[bar[Fu],i2]*Mass[Fu,i3],TfFbFbFbS,{L, L, L}}},{{{{bar[Fu], i2}, {Fu, i1}, {hh, gE1}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i1}, {Fu, i3}, {hh, i4}}, C[Fu, hh, bar[Fu]]}, {{{bar[Fu], i3}, {Fu, i2}, {hh, i4}}, C[Fu, hh, bar[Fu]]}}},
{{{Fv, i1, 6}, {Fv, i2, 6}, {Fv, i3, 6}, {Ah, i4, 4}},{{-1*Mass[Fv,i3],TfFFFbS,{L, R, R}},{-1*Mass[Fv,i2],TfFFbFS,{L, R, L}},{1*Mass[Fv,i1]*Mass[Fv,i2]*Mass[Fv,i3],TfFbFbFbS,{L, L, L}}},{{{{Fv, i1}, {Fv, i2}, {hh, gE1}}, C[Fv, Fv, hh]}, {{{Fv, i1}, {Fv, i3}, {Ah, i4}}, C[Ah, Fv, Fv]}, {{{Fv, i2}, {Fv, i3}, {Ah, i4}}, C[Ah, Fv, Fv]}}},
{{{Fv, i1, 6}, {Fv, i2, 6}, {Fe, i3, 3}, {conj[Hpm], i4, 4}},{{-2*Mass[Fe,i3],TfFFFbS,{L, R, R}},{-2*Mass[Fv,i2],TfFFbFS,{L, R, L}},{2*Mass[Fv,i1]*Mass[Fv,i2]*Mass[Fe,i3],TfFbFbFbS,{L, L, L}}},{{{{Fv, i1}, {Fv, i2}, {hh, gE1}}, C[Fv, Fv, hh]}, {{{Fv, i1}, {Fe, i3}, {conj[Hpm], i4}}, C[Fe, Fv, conj[Hpm]]}, {{{bar[Fe], i3}, {Fv, i2}, {Hpm, i4}}, C[Fv, Hpm, bar[Fe]]}}},
{{{Fv, i1, 6}, {Fv, i2, 6}, {Fv, i3, 6}, {hh, i4, 4}},{{-1*Mass[Fv,i3],TfFFFbS,{L, R, R}},{-1*Mass[Fv,i2],TfFFbFS,{L, R, L}},{1*Mass[Fv,i1]*Mass[Fv,i2]*Mass[Fv,i3],TfFbFbFbS,{L, L, L}}},{{{{Fv, i1}, {Fv, i2}, {hh, gE1}}, C[Fv, Fv, hh]}, {{{Fv, i1}, {Fv, i3}, {hh, i4}}, C[Fv, Fv, hh]}, {{{Fv, i2}, {Fv, i3}, {hh, i4}}, C[Fv, Fv, hh]}}}
}},
{ToFV,{
{{{Fd, i1, 3}},{{-4*Mass[Fd,i1],TfFV,{L, 0, 0}}},{{{{bar[Fd], i1}, {Fd, i1}, {hh, gE1}}, C[Fd, hh, bar[Fd]]}, {{}, g3}, {{}, g3}}},
{{{Fu, i1, 3}},{{-4*Mass[Fu,i1],TfFV,{L, 0, 0}}},{{{{bar[Fu], i1}, {Fu, i1}, {hh, gE1}}, C[Fu, hh, bar[Fu]]}, {{}, g3}, {{}, g3}}}
}}
}
