{{{bar[gG[{ct1}]], gG[{ct2}], VG[{ct3, lt3}]}, {g3*fSU3[ct1, ct2, ct3], 
   Mom[gG[{ct2}], lt3]}}, {{bar[gWLm], gP, VWLm[{lt3}]}, 
  {I*(g2*Cos[PhiW]^2*ZZ[2, 1] + gR*Sin[PhiW]^2*ZZ[3, 1]), Mom[gP, lt3]}}, 
 {{bar[gWRm], gP, VWLm[{lt3}]}, 
  {(-I)*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 1] - gR*ZZ[3, 1]), Mom[gP, lt3]}}, 
 {{bar[gWLm], gP, VWRm[{lt3}]}, 
  {(-I)*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 1] - gR*ZZ[3, 1]), Mom[gP, lt3]}}, 
 {{bar[gWRm], gP, VWRm[{lt3}]}, 
  {I*(g2*Sin[PhiW]^2*ZZ[2, 1] + gR*Cos[PhiW]^2*ZZ[3, 1]), Mom[gP, lt3]}}, 
 {{bar[gWLmC], gP, conj[VWLm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 1]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 1]]*Sin[PhiW]^2), 
   Mom[gP, lt3]}}, {{bar[gWLmC], gP, conj[VWRm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 1]] - gR*conj[ZZ[3, 1]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gP, lt3]}}, {{bar[gWRmC], gP, conj[VWLm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 1]] - gR*conj[ZZ[3, 1]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gP, lt3]}}, {{bar[gWRmC], gP, conj[VWRm[{lt3}]]}, 
  {(-I)*(gR*conj[ZZ[3, 1]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 1]]*Sin[PhiW]^2), 
   Mom[gP, lt3]}}, {{bar[gWLm], gWLm, VP[{lt3}]}, 
  {(-I)*(g2*Cos[PhiW]^2*ZZ[2, 1] + gR*Sin[PhiW]^2*ZZ[3, 1]), 
   Mom[gWLm, lt3]}}, {{bar[gWRm], gWLm, VP[{lt3}]}, 
  {I*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 1] - gR*ZZ[3, 1]), Mom[gWLm, lt3]}}, 
 {{bar[gWLm], gWLm, VZ[{lt3}]}, 
  {(-I)*(g2*Cos[PhiW]^2*ZZ[2, 2] + gR*Sin[PhiW]^2*ZZ[3, 2]), 
   Mom[gWLm, lt3]}}, {{bar[gWRm], gWLm, VZ[{lt3}]}, 
  {I*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 2] - gR*ZZ[3, 2]), Mom[gWLm, lt3]}}, 
 {{bar[gWLm], gWLm, VZR[{lt3}]}, 
  {(-I)*(g2*Cos[PhiW]^2*ZZ[2, 3] + gR*Sin[PhiW]^2*ZZ[3, 3]), 
   Mom[gWLm, lt3]}}, {{bar[gWRm], gWLm, VZR[{lt3}]}, 
  {I*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 3] - gR*ZZ[3, 3]), Mom[gWLm, lt3]}}, 
 {{bar[gP], gWLm, conj[VWLm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 1]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 1]]*Sin[PhiW]^2), 
   Mom[gWLm, lt3]}}, {{bar[gP], gWLm, conj[VWRm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 1]] - gR*conj[ZZ[3, 1]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLm, lt3]}}, {{bar[gZ], gWLm, conj[VWLm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 2]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 2]]*Sin[PhiW]^2), 
   Mom[gWLm, lt3]}}, {{bar[gZ], gWLm, conj[VWRm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 2]] - gR*conj[ZZ[3, 2]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLm, lt3]}}, {{bar[gZR], gWLm, conj[VWLm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 3]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 3]]*Sin[PhiW]^2), 
   Mom[gWLm, lt3]}}, {{bar[gZR], gWLm, conj[VWRm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 3]] - gR*conj[ZZ[3, 3]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLm, lt3]}}, {{bar[gWLmC], gWLmC, VP[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 1]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 1]]*Sin[PhiW]^2), 
   Mom[gWLmC, lt3]}}, {{bar[gWRmC], gWLmC, VP[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 1]] - gR*conj[ZZ[3, 1]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLmC, lt3]}}, {{bar[gP], gWLmC, VWLm[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 1]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 1]]*Sin[PhiW]^2), 
   Mom[gWLmC, lt3]}}, {{bar[gZ], gWLmC, VWLm[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 2]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 2]]*Sin[PhiW]^2), 
   Mom[gWLmC, lt3]}}, {{bar[gZR], gWLmC, VWLm[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 3]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 3]]*Sin[PhiW]^2), 
   Mom[gWLmC, lt3]}}, {{bar[gP], gWLmC, VWRm[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 1]] - gR*conj[ZZ[3, 1]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLmC, lt3]}}, {{bar[gZ], gWLmC, VWRm[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 2]] - gR*conj[ZZ[3, 2]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLmC, lt3]}}, {{bar[gZR], gWLmC, VWRm[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 3]] - gR*conj[ZZ[3, 3]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLmC, lt3]}}, {{bar[gWLmC], gWLmC, VZ[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 2]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 2]]*Sin[PhiW]^2), 
   Mom[gWLmC, lt3]}}, {{bar[gWRmC], gWLmC, VZ[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 2]] - gR*conj[ZZ[3, 2]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLmC, lt3]}}, {{bar[gWLmC], gWLmC, VZR[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 3]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 3]]*Sin[PhiW]^2), 
   Mom[gWLmC, lt3]}}, {{bar[gWRmC], gWLmC, VZR[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 3]] - gR*conj[ZZ[3, 3]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWLmC, lt3]}}, {{bar[gWLm], gWRm, VP[{lt3}]}, 
  {I*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 1] - gR*ZZ[3, 1]), Mom[gWRm, lt3]}}, 
 {{bar[gWRm], gWRm, VP[{lt3}]}, 
  {(-I)*(g2*Sin[PhiW]^2*ZZ[2, 1] + gR*Cos[PhiW]^2*ZZ[3, 1]), 
   Mom[gWRm, lt3]}}, {{bar[gWLm], gWRm, VZ[{lt3}]}, 
  {I*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 2] - gR*ZZ[3, 2]), Mom[gWRm, lt3]}}, 
 {{bar[gWRm], gWRm, VZ[{lt3}]}, 
  {(-I)*(g2*Sin[PhiW]^2*ZZ[2, 2] + gR*Cos[PhiW]^2*ZZ[3, 2]), 
   Mom[gWRm, lt3]}}, {{bar[gWLm], gWRm, VZR[{lt3}]}, 
  {I*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 3] - gR*ZZ[3, 3]), Mom[gWRm, lt3]}}, 
 {{bar[gWRm], gWRm, VZR[{lt3}]}, 
  {(-I)*(g2*Sin[PhiW]^2*ZZ[2, 3] + gR*Cos[PhiW]^2*ZZ[3, 3]), 
   Mom[gWRm, lt3]}}, {{bar[gP], gWRm, conj[VWLm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 1]] - gR*conj[ZZ[3, 1]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRm, lt3]}}, {{bar[gP], gWRm, conj[VWRm[{lt3}]]}, 
  {I*(gR*conj[ZZ[3, 1]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 1]]*Sin[PhiW]^2), 
   Mom[gWRm, lt3]}}, {{bar[gZ], gWRm, conj[VWLm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 2]] - gR*conj[ZZ[3, 2]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRm, lt3]}}, {{bar[gZ], gWRm, conj[VWRm[{lt3}]]}, 
  {I*(gR*conj[ZZ[3, 2]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 2]]*Sin[PhiW]^2), 
   Mom[gWRm, lt3]}}, {{bar[gZR], gWRm, conj[VWLm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 3]] - gR*conj[ZZ[3, 3]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRm, lt3]}}, {{bar[gZR], gWRm, conj[VWRm[{lt3}]]}, 
  {I*(gR*conj[ZZ[3, 3]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 3]]*Sin[PhiW]^2), 
   Mom[gWRm, lt3]}}, {{bar[gWLmC], gWRmC, VP[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 1]] - gR*conj[ZZ[3, 1]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRmC, lt3]}}, {{bar[gWRmC], gWRmC, VP[{lt3}]}, 
  {I*(gR*conj[ZZ[3, 1]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 1]]*Sin[PhiW]^2), 
   Mom[gWRmC, lt3]}}, {{bar[gP], gWRmC, VWLm[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 1]] - gR*conj[ZZ[3, 1]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRmC, lt3]}}, {{bar[gZ], gWRmC, VWLm[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 2]] - gR*conj[ZZ[3, 2]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRmC, lt3]}}, {{bar[gZR], gWRmC, VWLm[{lt3}]}, 
  {I*(g2*conj[ZZ[2, 3]] - gR*conj[ZZ[3, 3]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRmC, lt3]}}, {{bar[gP], gWRmC, VWRm[{lt3}]}, 
  {(-I)*(gR*conj[ZZ[3, 1]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 1]]*Sin[PhiW]^2), 
   Mom[gWRmC, lt3]}}, {{bar[gZ], gWRmC, VWRm[{lt3}]}, 
  {(-I)*(gR*conj[ZZ[3, 2]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 2]]*Sin[PhiW]^2), 
   Mom[gWRmC, lt3]}}, {{bar[gZR], gWRmC, VWRm[{lt3}]}, 
  {(-I)*(gR*conj[ZZ[3, 3]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 3]]*Sin[PhiW]^2), 
   Mom[gWRmC, lt3]}}, {{bar[gWLmC], gWRmC, VZ[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 2]] - gR*conj[ZZ[3, 2]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRmC, lt3]}}, {{bar[gWRmC], gWRmC, VZ[{lt3}]}, 
  {I*(gR*conj[ZZ[3, 2]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 2]]*Sin[PhiW]^2), 
   Mom[gWRmC, lt3]}}, {{bar[gWLmC], gWRmC, VZR[{lt3}]}, 
  {(-I)*(g2*conj[ZZ[2, 3]] - gR*conj[ZZ[3, 3]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gWRmC, lt3]}}, {{bar[gWRmC], gWRmC, VZR[{lt3}]}, 
  {I*(gR*conj[ZZ[3, 3]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 3]]*Sin[PhiW]^2), 
   Mom[gWRmC, lt3]}}, {{bar[gWLm], gZ, VWLm[{lt3}]}, 
  {I*(g2*Cos[PhiW]^2*ZZ[2, 2] + gR*Sin[PhiW]^2*ZZ[3, 2]), Mom[gZ, lt3]}}, 
 {{bar[gWRm], gZ, VWLm[{lt3}]}, 
  {(-I)*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 2] - gR*ZZ[3, 2]), Mom[gZ, lt3]}}, 
 {{bar[gWLm], gZ, VWRm[{lt3}]}, 
  {(-I)*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 2] - gR*ZZ[3, 2]), Mom[gZ, lt3]}}, 
 {{bar[gWRm], gZ, VWRm[{lt3}]}, 
  {I*(g2*Sin[PhiW]^2*ZZ[2, 2] + gR*Cos[PhiW]^2*ZZ[3, 2]), Mom[gZ, lt3]}}, 
 {{bar[gWLmC], gZ, conj[VWLm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 2]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 2]]*Sin[PhiW]^2), 
   Mom[gZ, lt3]}}, {{bar[gWLmC], gZ, conj[VWRm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 2]] - gR*conj[ZZ[3, 2]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gZ, lt3]}}, {{bar[gWRmC], gZ, conj[VWLm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 2]] - gR*conj[ZZ[3, 2]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gZ, lt3]}}, {{bar[gWRmC], gZ, conj[VWRm[{lt3}]]}, 
  {(-I)*(gR*conj[ZZ[3, 2]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 2]]*Sin[PhiW]^2), 
   Mom[gZ, lt3]}}, {{bar[gWLm], gZR, VWLm[{lt3}]}, 
  {I*(g2*Cos[PhiW]^2*ZZ[2, 3] + gR*Sin[PhiW]^2*ZZ[3, 3]), Mom[gZR, lt3]}}, 
 {{bar[gWRm], gZR, VWLm[{lt3}]}, 
  {(-I)*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 3] - gR*ZZ[3, 3]), Mom[gZR, lt3]}}, 
 {{bar[gWLm], gZR, VWRm[{lt3}]}, 
  {(-I)*Cos[PhiW]*Sin[PhiW]*(g2*ZZ[2, 3] - gR*ZZ[3, 3]), Mom[gZR, lt3]}}, 
 {{bar[gWRm], gZR, VWRm[{lt3}]}, 
  {I*(g2*Sin[PhiW]^2*ZZ[2, 3] + gR*Cos[PhiW]^2*ZZ[3, 3]), Mom[gZR, lt3]}}, 
 {{bar[gWLmC], gZR, conj[VWLm[{lt3}]]}, 
  {(-I)*(g2*conj[ZZ[2, 3]]*Cos[PhiW]^2 + gR*conj[ZZ[3, 3]]*Sin[PhiW]^2), 
   Mom[gZR, lt3]}}, {{bar[gWLmC], gZR, conj[VWRm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 3]] - gR*conj[ZZ[3, 3]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gZR, lt3]}}, {{bar[gWRmC], gZR, conj[VWLm[{lt3}]]}, 
  {I*(g2*conj[ZZ[2, 3]] - gR*conj[ZZ[3, 3]])*Cos[PhiW]*Sin[PhiW], 
   Mom[gZR, lt3]}}, {{bar[gWRmC], gZR, conj[VWRm[{lt3}]]}, 
  {(-I)*(gR*conj[ZZ[3, 3]]*Cos[PhiW]^2 + g2*conj[ZZ[2, 3]]*Sin[PhiW]^2), 
   Mom[gZR, lt3]}}}
