(* ----------------------------------------------------------------------------- *) 
(* This model was automatically created by SARAH version4.13.0  *) 
(* SARAH References: arXiv:0806.0538, 0909.2863, 1002.0840, 1207.0906, 1309.7223 *) 
(* (c) Florian Staub, 2013  *) 
(* ----------------------------------------------------------------------------- *) 
(* File created at 0:19 on 10.2.2021  *) 
(* ---------------------------------------------------------------------- *) 
 
 
LoopContributions[PengS2d2nu]={
(* Ah,Fd, Internal:bar[Fd], Propagator: hh*) 
{{Ah,Fd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[Ah][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* hh,Fd, Internal:bar[Fd], Propagator: hh*) 
{{hh,Fd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[hh][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* VZ,Fd, Internal:bar[Fd], Propagator: hh*) 
{{VZ,Fd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mV1 -> M[VZ],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* VZR,Fd, Internal:bar[Fd], Propagator: hh*) 
{{VZR,Fd, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZR][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mV1 -> M[VZR],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* bar[Fu],Hpm, Internal:bar[Fd], Propagator: hh*) 
{{bar[Fu],Hpm, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Fu, Hpm][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mS1 -> M[Hpm][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* bar[Fu],VWLm, Internal:bar[Fd], Propagator: hh*) 
{{bar[Fu],VWLm, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mV1 -> M[VWLm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* bar[Fu],VWRm, Internal:bar[Fd], Propagator: hh*) 
{{bar[Fu],VWRm, Internal->bar[Fd], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mV1 -> M[VWRm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[hh][iProp]}},
(* Fd,Ah, Internal:Fd, Propagator: hh*) 
{{Fd,Ah, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i2],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mS1 -> M[Ah][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Fd,hh, Internal:Fd, Propagator: hh*) 
{{Fd,hh, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i2],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mS1 -> M[hh][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Fd,VZ, Internal:Fd, Propagator: hh*) 
{{Fd,VZ, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, VZ][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mV1 -> M[VZ],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Fd,VZR, Internal:Fd, Propagator: hh*) 
{{Fd,VZR, Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, VZR][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZR][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mV1 -> M[VZR],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Hpm,bar[Fu], Internal:Fd, Propagator: hh*) 
{{Hpm,bar[Fu], Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,i3,i1],coup2R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i2,i1],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* VWLm,bar[Fu], Internal:Fd, Propagator: hh*) 
{{VWLm,bar[Fu], Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i2],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mV1 -> M[VWLm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* VWRm,bar[Fu], Internal:Fd, Propagator: hh*) 
{{VWRm,bar[Fu], Internal->Fd, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i2],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},{mV1 -> M[VWRm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[hh][iProp]}},
(* Ah,Fv, Internal:Fv, Propagator: hh*) 
{{Ah,Fv, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, Ah][L][i3,i2,i1],coup2R -> Cp[Fv, Fv, Ah][R][i3,i2,i1],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[Ah][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Fe,Hpm, Internal:Fv, Propagator: hh*) 
{{Fe,Hpm, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Fe,VWLm, Internal:Fv, Propagator: hh*) 
{{Fe,VWLm, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,i3],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWLm],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Fe,VWRm, Internal:Fv, Propagator: hh*) 
{{Fe,VWRm, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,i3],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWRm],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Fv,hh, Internal:Fv, Propagator: hh*) 
{{Fv,hh, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, hh][L][i3,i1,i2],coup2R -> Cp[Fv, Fv, hh][R][i3,i1,i2],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mS1 -> M[hh][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Fv,VZ, Internal:Fv, Propagator: hh*) 
{{Fv,VZ, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZ][L][i3,i1],coup2R -> Cp[Fv, Fv, VZ][R][i3,i1],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mV1 -> M[VZ],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Fv,VZR, Internal:Fv, Propagator: hh*) 
{{Fv,VZR, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZR][L][i3,i1],coup2R -> Cp[Fv, Fv, VZR][R][i3,i1],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mV1 -> M[VZR],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Hpm,Fe, Internal:Fv, Propagator: hh*) 
{{Hpm,Fe, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][i3,i2,i1],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* VWLm,Fe, Internal:Fv, Propagator: hh*) 
{{VWLm,Fe, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][i3,i2],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VWLm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* VWRm,Fe, Internal:Fv, Propagator: hh*) 
{{VWRm,Fe, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][i3,i2],coup3L -> Cp[Fv, Fv, hh][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, hh][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VWRm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[hh][iProp]}},
(* Fv,Ah, Internal:Fv, Propagator: hh*) 
{{Fv,Ah, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fv, Ah][L][i1,i3,i2],coup2R -> Cp[Fv, Fv, Ah][R][i1,i3,i2],coup1L -> Cp[Fv, Fv, Ah][L][gt4,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mS1 -> M[Ah][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Hpm,Fe, Internal:Fv, Propagator: hh*) 
{{Hpm,Fe, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][i3,i2,i1],coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt4,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt4,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* VWLm,Fe, Internal:Fv, Propagator: hh*) 
{{VWLm,Fe, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][i3,i2],coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt4],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt4],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VWLm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* VWRm,Fe, Internal:Fv, Propagator: hh*) 
{{VWRm,Fe, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][i3,i2],coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt4],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt4],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VWRm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* hh,Fv, Internal:Fv, Propagator: hh*) 
{{hh,Fv, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fv, hh][L][i2,i3,i1],coup2R -> Cp[Fv, Fv, hh][R][i2,i3,i1],coup1L -> Cp[Fv, Fv, hh][L][gt4,i2,i1],coup1R -> Cp[Fv, Fv, hh][R][gt4,i2,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mS1 -> M[hh][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* VZ,Fv, Internal:Fv, Propagator: hh*) 
{{VZ,Fv, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fv, VZ][L][i2,i3],coup2R -> Cp[Fv, Fv, VZ][R][i2,i3],coup1L -> Cp[Fv, Fv, VZ][L][gt4,i2],coup1R -> Cp[Fv, Fv, VZ][R][gt4,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VZ],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* VZR,Fv, Internal:Fv, Propagator: hh*) 
{{VZR,Fv, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fv, VZR][L][i2,i3],coup2R -> Cp[Fv, Fv, VZR][R][i2,i3],coup1L -> Cp[Fv, Fv, VZR][L][gt4,i2],coup1R -> Cp[Fv, Fv, VZR][R][gt4,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mV1 -> M[VZR],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Fe,Hpm, Internal:Fv, Propagator: hh*) 
{{Fe,Hpm, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Fe,VWLm, Internal:Fv, Propagator: hh*) 
{{Fe,VWLm, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,i3],coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWLm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}},
(* Fe,VWRm, Internal:Fv, Propagator: hh*) 
{{Fe,VWRm, Internal->Fv, Propagator ->hh},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,i3],coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWRm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[hh][iProp]}}
(* Ah,Fd, Internal:bar[Fd], Propagator: Ah*) 
{{Ah,Fd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[Ah][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* hh,Fd, Internal:bar[Fd], Propagator: Ah*) 
{{hh,Fd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[hh][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* VZ,Fd, Internal:bar[Fd], Propagator: Ah*) 
{{VZ,Fd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mV1 -> M[VZ],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* VZR,Fd, Internal:bar[Fd], Propagator: Ah*) 
{{VZR,Fd, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZR][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mV1 -> M[VZR],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* bar[Fu],Hpm, Internal:bar[Fd], Propagator: Ah*) 
{{bar[Fu],Hpm, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Fu, Hpm][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mS1 -> M[Hpm][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* bar[Fu],VWLm, Internal:bar[Fd], Propagator: Ah*) 
{{bar[Fu],VWLm, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mV1 -> M[VWLm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* bar[Fu],VWRm, Internal:bar[Fd], Propagator: Ah*) 
{{bar[Fu],VWRm, Internal->bar[Fd], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fu][i1],mV1 -> M[VWRm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[Ah][iProp]}},
(* Fd,Ah, Internal:Fd, Propagator: Ah*) 
{{Fd,Ah, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mS1 -> M[Ah][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Fd,hh, Internal:Fd, Propagator: Ah*) 
{{Fd,hh, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mS1 -> M[hh][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Fd,VZ, Internal:Fd, Propagator: Ah*) 
{{Fd,VZ, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, VZ][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mV1 -> M[VZ],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Fd,VZR, Internal:Fd, Propagator: Ah*) 
{{Fd,VZR, Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fd], Fd, VZR][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZR][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mF1 -> M[Fd][i1],mV1 -> M[VZR],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Hpm,bar[Fu], Internal:Fd, Propagator: Ah*) 
{{Hpm,bar[Fu], Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,i3,i1],coup2R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i2,i1],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* VWLm,bar[Fu], Internal:Fd, Propagator: Ah*) 
{{VWLm,bar[Fu], Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mV1 -> M[VWLm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* VWRm,bar[Fu], Internal:Fd, Propagator: Ah*) 
{{VWRm,bar[Fu], Internal->Fd, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1,iProp],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1,iProp],coup2L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},{mV1 -> M[VWRm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[Ah][iProp]}},
(* Ah,Fv, Internal:Fv, Propagator: Ah*) 
{{Ah,Fv, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, Ah][L][i3,i2,i1],coup2R -> Cp[Fv, Fv, Ah][R][i3,i2,i1],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[Ah][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Fe,Hpm, Internal:Fv, Propagator: Ah*) 
{{Fe,Hpm, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Fe,VWLm, Internal:Fv, Propagator: Ah*) 
{{Fe,VWLm, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,i3],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWLm],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Fe,VWRm, Internal:Fv, Propagator: Ah*) 
{{Fe,VWRm, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,i3],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWRm],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Fv,hh, Internal:Fv, Propagator: Ah*) 
{{Fv,hh, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, hh][L][i3,i1,i2],coup2R -> Cp[Fv, Fv, hh][R][i3,i1,i2],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mS1 -> M[hh][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Fv,VZ, Internal:Fv, Propagator: Ah*) 
{{Fv,VZ, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZ][L][i3,i1],coup2R -> Cp[Fv, Fv, VZ][R][i3,i1],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mV1 -> M[VZ],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Fv,VZR, Internal:Fv, Propagator: Ah*) 
{{Fv,VZR, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZR][L][i3,i1],coup2R -> Cp[Fv, Fv, VZR][R][i3,i1],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mV1 -> M[VZR],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Hpm,Fe, Internal:Fv, Propagator: Ah*) 
{{Hpm,Fe, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][i3,i2,i1],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* VWLm,Fe, Internal:Fv, Propagator: Ah*) 
{{VWLm,Fe, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][i3,i2],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VWLm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* VWRm,Fe, Internal:Fv, Propagator: Ah*) 
{{VWRm,Fe, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][i3,i2],coup3L -> Cp[Fv, Fv, Ah][L][gt4,i3,iProp],coup3R -> Cp[Fv, Fv, Ah][R][gt4,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VWRm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[Ah][iProp]}},
(* Fv,Ah, Internal:Fv, Propagator: Ah*) 
{{Fv,Ah, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fv, Ah][L][i1,i3,i2],coup2R -> Cp[Fv, Fv, Ah][R][i1,i3,i2],coup1L -> Cp[Fv, Fv, Ah][L][gt4,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fv][i1],mS1 -> M[Ah][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Hpm,Fe, Internal:Fv, Propagator: Ah*) 
{{Hpm,Fe, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][i3,i2,i1],coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt4,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt4,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* VWLm,Fe, Internal:Fv, Propagator: Ah*) 
{{VWLm,Fe, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][i3,i2],coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt4],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt4],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VWLm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* VWRm,Fe, Internal:Fv, Propagator: Ah*) 
{{VWRm,Fe, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][i3,i2],coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt4],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt4],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VWRm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* hh,Fv, Internal:Fv, Propagator: Ah*) 
{{hh,Fv, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fv, hh][L][i2,i3,i1],coup2R -> Cp[Fv, Fv, hh][R][i2,i3,i1],coup1L -> Cp[Fv, Fv, hh][L][gt4,i2,i1],coup1R -> Cp[Fv, Fv, hh][R][gt4,i2,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mS1 -> M[hh][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* VZ,Fv, Internal:Fv, Propagator: Ah*) 
{{VZ,Fv, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fv, VZ][L][i2,i3],coup2R -> Cp[Fv, Fv, VZ][R][i2,i3],coup1L -> Cp[Fv, Fv, VZ][L][gt4,i2],coup1R -> Cp[Fv, Fv, VZ][R][gt4,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VZ],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* VZR,Fv, Internal:Fv, Propagator: Ah*) 
{{VZR,Fv, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[Fv, Fv, VZR][L][i2,i3],coup2R -> Cp[Fv, Fv, VZR][R][i2,i3],coup1L -> Cp[Fv, Fv, VZR][L][gt4,i2],coup1R -> Cp[Fv, Fv, VZR][R][gt4,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mV1 -> M[VZR],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Fe,Hpm, Internal:Fv, Propagator: Ah*) 
{{Fe,Hpm, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Fe,VWLm, Internal:Fv, Propagator: Ah*) 
{{Fe,VWLm, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,i3],coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWLm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}},
(* Fe,VWRm, Internal:Fv, Propagator: Ah*) 
{{Fe,VWRm, Internal->Fv, Propagator ->Ah},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3,iProp],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3,iProp],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,i3],coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},{mF1 -> M[Fe][i1],mV1 -> M[VWRm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[Ah][iProp]}}
(* Ah,Fd,Fd, Propagator: hh*) 
{{Ah,Fd,Fd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* hh,Fd,Fd, Propagator: hh*) 
{{hh,Fd,Fd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* VZ,Fd,Fd, Propagator: hh*) 
{{VZ,Fd,Fd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* VZR,Fd,Fd, Propagator: hh*) 
{{VZR,Fd,Fd, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, hh][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],Ah,Ah, Propagator: hh*) 
{{bar[Fd],Ah,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, Ah, hh][i3,i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZ,Ah, Propagator: hh*) 
{{bar[Fd],VZ,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZ][i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZR,Ah, Propagator: hh*) 
{{bar[Fd],VZR,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZR][i3,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],hh,hh, Propagator: hh*) 
{{bar[Fd],hh,hh, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[hh, hh, hh][iProp,i3,i2],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],Ah,VZ, Propagator: hh*) 
{{bar[Fd],Ah,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[Ah, hh, VZ][i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZ,VZ, Propagator: hh*) 
{{bar[Fd],VZ,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[hh, VZ, VZ][iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZR,VZ, Propagator: hh*) 
{{bar[Fd],VZR,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[hh, VZ, VZR][iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],Ah,VZR, Propagator: hh*) 
{{bar[Fd],Ah,VZR, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup3 -> Cp[Ah, hh, VZR][i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZ,VZR, Propagator: hh*) 
{{bar[Fd],VZ,VZR, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup3 -> Cp[hh, VZ, VZR][iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fd],VZR,VZR, Propagator: hh*) 
{{bar[Fd],VZR,VZR, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup3 -> Cp[hh, VZR, VZR][iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],Hpm,Hpm, Propagator: hh*) 
{{bar[Fu],Hpm,Hpm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[hh, Hpm, conj[Hpm]][iProp,i2,i3],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],VWLm,Hpm, Propagator: hh*) 
{{bar[Fu],VWLm,Hpm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[hh, conj[Hpm], VWLm][iProp,i3],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],VWRm,Hpm, Propagator: hh*) 
{{bar[Fu],VWRm,Hpm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[hh, conj[Hpm], VWRm][iProp,i3],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],Hpm,VWLm, Propagator: hh*) 
{{bar[Fu],Hpm,VWLm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[hh, Hpm, conj[VWLm]][iProp,i2],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],VWLm,VWLm, Propagator: hh*) 
{{bar[Fu],VWLm,VWLm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[hh, conj[VWLm], VWLm][iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],VWRm,VWLm, Propagator: hh*) 
{{bar[Fu],VWRm,VWLm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[hh, conj[VWLm], VWRm][iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],Hpm,VWRm, Propagator: hh*) 
{{bar[Fu],Hpm,VWRm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[hh, Hpm, conj[VWRm]][iProp,i2],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],VWLm,VWRm, Propagator: hh*) 
{{bar[Fu],VWLm,VWRm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[hh, conj[VWRm], VWLm][iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* bar[Fu],VWRm,VWRm, Propagator: hh*) 
{{bar[Fu],VWRm,VWRm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[hh, conj[VWRm], VWRm][iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* conj[Hpm],Fu,Fu, Propagator: hh*) 
{{conj[Hpm],Fu,Fu, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,gt1,i1],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i3,i1],coup3L -> Cp[bar[Fu], Fu, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, hh][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* conj[VWLm],Fu,Fu, Propagator: hh*) 
{{conj[VWLm],Fu,Fu, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, hh][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* conj[VWRm],Fu,Fu, Propagator: hh*) 
{{conj[VWRm],Fu,Fu, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, hh][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, hh][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, hh][R][gt4,gt3,iProp]},MP -> M[hh][iProp],},
(* Ah,Fv,Fv, Propagator: hh*) 
{{Ah,Fv,Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i3,i1],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i3,i1],coup3L -> Cp[Fv, Fv, hh][L][i3,i2,iProp],coup3R -> Cp[Fv, Fv, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,Hpm,Hpm, Propagator: hh*) 
{{Fe,Hpm,Hpm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[hh, Hpm, conj[Hpm]][iProp,i2,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,VWLm,Hpm, Propagator: hh*) 
{{Fe,VWLm,Hpm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[hh, conj[Hpm], VWLm][iProp,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,VWRm,Hpm, Propagator: hh*) 
{{Fe,VWRm,Hpm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[hh, conj[Hpm], VWRm][iProp,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,Hpm,VWLm, Propagator: hh*) 
{{Fe,Hpm,VWLm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[hh, Hpm, conj[VWLm]][iProp,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,VWLm,VWLm, Propagator: hh*) 
{{Fe,VWLm,VWLm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[hh, conj[VWLm], VWLm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,VWRm,VWLm, Propagator: hh*) 
{{Fe,VWRm,VWLm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[hh, conj[VWLm], VWRm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,Hpm,VWRm, Propagator: hh*) 
{{Fe,Hpm,VWRm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[hh, Hpm, conj[VWRm]][iProp,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,VWLm,VWRm, Propagator: hh*) 
{{Fe,VWLm,VWRm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[hh, conj[VWRm], VWLm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fe,VWRm,VWRm, Propagator: hh*) 
{{Fe,VWRm,VWRm, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[hh, conj[VWRm], VWRm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,Ah,Ah, Propagator: hh*) 
{{Fv,Ah,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, Ah, hh][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,VZ,Ah, Propagator: hh*) 
{{Fv,VZ,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZ][i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,VZR,Ah, Propagator: hh*) 
{{Fv,VZR,Ah, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZR][i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,hh,hh, Propagator: hh*) 
{{Fv,hh,hh, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[hh, hh, hh][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,Ah,VZ, Propagator: hh*) 
{{Fv,Ah,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i1],coup3 -> Cp[Ah, hh, VZ][i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,VZ,VZ, Propagator: hh*) 
{{Fv,VZ,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i1],coup3 -> Cp[hh, VZ, VZ][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,VZR,VZ, Propagator: hh*) 
{{Fv,VZR,VZ, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i1],coup3 -> Cp[hh, VZ, VZR][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,Ah,VZR, Propagator: hh*) 
{{Fv,Ah,VZR, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i1],coup3 -> Cp[Ah, hh, VZR][i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,VZ,VZR, Propagator: hh*) 
{{Fv,VZ,VZR, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i1],coup3 -> Cp[hh, VZ, VZR][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Fv,VZR,VZR, Propagator: hh*) 
{{Fv,VZR,VZR, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i1],coup3 -> Cp[hh, VZR, VZR][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* hh,Fv,Fv, Propagator: hh*) 
{{hh,Fv,Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, hh][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i3,i1],coup2R -> Cp[Fv, Fv, hh][R][gt4,i3,i1],coup3L -> Cp[Fv, Fv, hh][L][i3,i2,iProp],coup3R -> Cp[Fv, Fv, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* Hpm,Fe,Fe, Propagator: hh*) 
{{Hpm,Fe,Fe, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i3,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i3,i1],coup3L -> Cp[bar[Fe], Fe, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* VWLm,Fe,Fe, Propagator: hh*) 
{{VWLm,Fe,Fe, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i3],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* VWRm,Fe,Fe, Propagator: hh*) 
{{VWRm,Fe,Fe, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i3],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, hh][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* VZ,Fv,Fv, Propagator: hh*) 
{{VZ,Fv,Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i2],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i2],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup3L -> Cp[Fv, Fv, hh][L][i3,i2,iProp],coup3R -> Cp[Fv, Fv, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* VZR,Fv,Fv, Propagator: hh*) 
{{VZR,Fv,Fv, Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i2],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i2],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup3L -> Cp[Fv, Fv, hh][L][i3,i2,iProp],coup3R -> Cp[Fv, Fv, hh][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[Hpm],conj[Hpm], Propagator: hh*) 
{{bar[Fe],conj[Hpm],conj[Hpm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[hh, Hpm, conj[Hpm]][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[VWLm],conj[Hpm], Propagator: hh*) 
{{bar[Fe],conj[VWLm],conj[Hpm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[hh, Hpm, conj[VWLm]][iProp,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[VWRm],conj[Hpm], Propagator: hh*) 
{{bar[Fe],conj[VWRm],conj[Hpm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[hh, Hpm, conj[VWRm]][iProp,i3],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[Hpm],conj[VWLm], Propagator: hh*) 
{{bar[Fe],conj[Hpm],conj[VWLm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[hh, conj[Hpm], VWLm][iProp,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[VWLm],conj[VWLm], Propagator: hh*) 
{{bar[Fe],conj[VWLm],conj[VWLm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[hh, conj[VWLm], VWLm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[VWRm],conj[VWLm], Propagator: hh*) 
{{bar[Fe],conj[VWRm],conj[VWLm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[hh, conj[VWRm], VWLm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[Hpm],conj[VWRm], Propagator: hh*) 
{{bar[Fe],conj[Hpm],conj[VWRm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[hh, conj[Hpm], VWRm][iProp,i2],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[VWLm],conj[VWRm], Propagator: hh*) 
{{bar[Fe],conj[VWLm],conj[VWRm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[hh, conj[VWLm], VWRm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* bar[Fe],conj[VWRm],conj[VWRm], Propagator: hh*) 
{{bar[Fe],conj[VWRm],conj[VWRm], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[hh, conj[VWRm], VWRm][iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* conj[Hpm],bar[Fe],bar[Fe], Propagator: hh*) 
{{conj[Hpm],bar[Fe],bar[Fe], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i2,i1],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i2,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i3,gt4,i1],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i3,gt4,i1],coup3L -> Cp[bar[Fe], Fe, hh][L][i2,i3,iProp],coup3R -> Cp[bar[Fe], Fe, hh][R][i2,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* conj[VWLm],bar[Fe],bar[Fe], Propagator: hh*) 
{{conj[VWLm],bar[Fe],bar[Fe], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i2],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i2],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i3,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i3,gt4],coup3L -> Cp[bar[Fe], Fe, hh][L][i2,i3,iProp],coup3R -> Cp[bar[Fe], Fe, hh][R][i2,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],},
(* conj[VWRm],bar[Fe],bar[Fe], Propagator: hh*) 
{{conj[VWRm],bar[Fe],bar[Fe], Propagator ->hh},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i2],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i2],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i3,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i3,gt4],coup3L -> Cp[bar[Fe], Fe, hh][L][i2,i3,iProp],coup3R -> Cp[bar[Fe], Fe, hh][R][i2,i3,iProp],coup4L -> Cp[bar[Fd], Fd, hh][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, hh][R][gt2,gt1,iProp]},MP -> M[hh][iProp],}
(* Ah,Fd,Fd, Propagator: Ah*) 
{{Ah,Fd,Fd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* hh,Fd,Fd, Propagator: Ah*) 
{{hh,Fd,Fd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* VZ,Fd,Fd, Propagator: Ah*) 
{{VZ,Fd,Fd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* VZR,Fd,Fd, Propagator: Ah*) 
{{VZR,Fd,Fd, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],hh,Ah, Propagator: Ah*) 
{{bar[Fd],hh,Ah, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, Ah, hh][iProp,i3,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],Ah,hh, Propagator: Ah*) 
{{bar[Fd],Ah,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, Ah, hh][iProp,i2,i3],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],VZ,hh, Propagator: Ah*) 
{{bar[Fd],VZ,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZ][iProp,i3],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],VZR,hh, Propagator: Ah*) 
{{bar[Fd],VZR,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZR][iProp,i3],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],hh,VZ, Propagator: Ah*) 
{{bar[Fd],hh,VZ, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[Ah, hh, VZ][iProp,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fd],hh,VZR, Propagator: Ah*) 
{{bar[Fd],hh,VZR, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup3 -> Cp[Ah, hh, VZR][iProp,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],Hpm,Hpm, Propagator: Ah*) 
{{bar[Fu],Hpm,Hpm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[Ah, Hpm, conj[Hpm]][iProp,i2,i3],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],VWLm,Hpm, Propagator: Ah*) 
{{bar[Fu],VWLm,Hpm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[Ah, conj[Hpm], VWLm][iProp,i3],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],VWRm,Hpm, Propagator: Ah*) 
{{bar[Fu],VWRm,Hpm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[Ah, conj[Hpm], VWRm][iProp,i3],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],Hpm,VWLm, Propagator: Ah*) 
{{bar[Fu],Hpm,VWLm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[Ah, Hpm, conj[VWLm]][iProp,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],VWRm,VWLm, Propagator: Ah*) 
{{bar[Fu],VWRm,VWLm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[Ah, conj[VWLm], VWRm][iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],Hpm,VWRm, Propagator: Ah*) 
{{bar[Fu],Hpm,VWRm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[Ah, Hpm, conj[VWRm]][iProp,i2],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* bar[Fu],VWLm,VWRm, Propagator: Ah*) 
{{bar[Fu],VWLm,VWRm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[Ah, conj[VWRm], VWLm][iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* conj[Hpm],Fu,Fu, Propagator: Ah*) 
{{conj[Hpm],Fu,Fu, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,gt1,i1],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i3,i1],coup3L -> Cp[bar[Fu], Fu, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, Ah][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* conj[VWLm],Fu,Fu, Propagator: Ah*) 
{{conj[VWLm],Fu,Fu, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, Ah][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* conj[VWRm],Fu,Fu, Propagator: Ah*) 
{{conj[VWRm],Fu,Fu, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fu], Fu, Ah][R][i3,i2,iProp],coup4L -> Cp[Fv, Fv, Ah][L][gt4,gt3,iProp],coup4R -> Cp[Fv, Fv, Ah][R][gt4,gt3,iProp]},MP -> M[Ah][iProp],},
(* Ah,Fv,Fv, Propagator: Ah*) 
{{Ah,Fv,Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i3,i1],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i3,i1],coup3L -> Cp[Fv, Fv, Ah][L][i3,i2,iProp],coup3R -> Cp[Fv, Fv, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fe,Hpm,Hpm, Propagator: Ah*) 
{{Fe,Hpm,Hpm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[Ah, Hpm, conj[Hpm]][iProp,i2,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fe,VWLm,Hpm, Propagator: Ah*) 
{{Fe,VWLm,Hpm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[Ah, conj[Hpm], VWLm][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fe,VWRm,Hpm, Propagator: Ah*) 
{{Fe,VWRm,Hpm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[Ah, conj[Hpm], VWRm][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fe,Hpm,VWLm, Propagator: Ah*) 
{{Fe,Hpm,VWLm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[Ah, Hpm, conj[VWLm]][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fe,VWRm,VWLm, Propagator: Ah*) 
{{Fe,VWRm,VWLm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[Ah, conj[VWLm], VWRm][iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fe,Hpm,VWRm, Propagator: Ah*) 
{{Fe,Hpm,VWRm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[Ah, Hpm, conj[VWRm]][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fe,VWLm,VWRm, Propagator: Ah*) 
{{Fe,VWLm,VWRm, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[Ah, conj[VWRm], VWLm][iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fv,hh,Ah, Propagator: Ah*) 
{{Fv,hh,Ah, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, Ah, hh][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fv,Ah,hh, Propagator: Ah*) 
{{Fv,Ah,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, Ah, hh][iProp,i2,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fv,VZ,hh, Propagator: Ah*) 
{{Fv,VZ,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZ][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fv,VZR,hh, Propagator: Ah*) 
{{Fv,VZR,hh, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZR][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fv,hh,VZ, Propagator: Ah*) 
{{Fv,hh,VZ, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i1],coup3 -> Cp[Ah, hh, VZ][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Fv,hh,VZR, Propagator: Ah*) 
{{Fv,hh,VZR, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i1],coup3 -> Cp[Ah, hh, VZR][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* hh,Fv,Fv, Propagator: Ah*) 
{{hh,Fv,Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, hh][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i3,i1],coup2R -> Cp[Fv, Fv, hh][R][gt4,i3,i1],coup3L -> Cp[Fv, Fv, Ah][L][i3,i2,iProp],coup3R -> Cp[Fv, Fv, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* Hpm,Fe,Fe, Propagator: Ah*) 
{{Hpm,Fe,Fe, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i3,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i3,i1],coup3L -> Cp[bar[Fe], Fe, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* VWLm,Fe,Fe, Propagator: Ah*) 
{{VWLm,Fe,Fe, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i3],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* VWRm,Fe,Fe, Propagator: Ah*) 
{{VWRm,Fe,Fe, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i3],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, Ah][L][i3,i2,iProp],coup3R -> Cp[bar[Fe], Fe, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* VZ,Fv,Fv, Propagator: Ah*) 
{{VZ,Fv,Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i2],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i2],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup3L -> Cp[Fv, Fv, Ah][L][i3,i2,iProp],coup3R -> Cp[Fv, Fv, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* VZR,Fv,Fv, Propagator: Ah*) 
{{VZR,Fv,Fv, Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i2],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i2],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup3L -> Cp[Fv, Fv, Ah][L][i3,i2,iProp],coup3R -> Cp[Fv, Fv, Ah][R][i3,i2,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[Hpm],conj[Hpm], Propagator: Ah*) 
{{bar[Fe],conj[Hpm],conj[Hpm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Ah, Hpm, conj[Hpm]][iProp,i3,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[VWLm],conj[Hpm], Propagator: Ah*) 
{{bar[Fe],conj[VWLm],conj[Hpm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Ah, Hpm, conj[VWLm]][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[VWRm],conj[Hpm], Propagator: Ah*) 
{{bar[Fe],conj[VWRm],conj[Hpm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Ah, Hpm, conj[VWRm]][iProp,i3],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[Hpm],conj[VWLm], Propagator: Ah*) 
{{bar[Fe],conj[Hpm],conj[VWLm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[Ah, conj[Hpm], VWLm][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[VWRm],conj[VWLm], Propagator: Ah*) 
{{bar[Fe],conj[VWRm],conj[VWLm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[Ah, conj[VWRm], VWLm][iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[Hpm],conj[VWRm], Propagator: Ah*) 
{{bar[Fe],conj[Hpm],conj[VWRm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[Ah, conj[Hpm], VWRm][iProp,i2],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* bar[Fe],conj[VWLm],conj[VWRm], Propagator: Ah*) 
{{bar[Fe],conj[VWLm],conj[VWRm], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[Ah, conj[VWLm], VWRm][iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* conj[Hpm],bar[Fe],bar[Fe], Propagator: Ah*) 
{{conj[Hpm],bar[Fe],bar[Fe], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i2,i1],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i2,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i3,gt4,i1],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i3,gt4,i1],coup3L -> Cp[bar[Fe], Fe, Ah][L][i2,i3,iProp],coup3R -> Cp[bar[Fe], Fe, Ah][R][i2,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* conj[VWLm],bar[Fe],bar[Fe], Propagator: Ah*) 
{{conj[VWLm],bar[Fe],bar[Fe], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i2],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i2],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i3,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i3,gt4],coup3L -> Cp[bar[Fe], Fe, Ah][L][i2,i3,iProp],coup3R -> Cp[bar[Fe], Fe, Ah][R][i2,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],},
(* conj[VWRm],bar[Fe],bar[Fe], Propagator: Ah*) 
{{conj[VWRm],bar[Fe],bar[Fe], Propagator ->Ah},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i2],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i2],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i3,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i3,gt4],coup3L -> Cp[bar[Fe], Fe, Ah][L][i2,i3,iProp],coup3R -> Cp[bar[Fe], Fe, Ah][R][i2,i3,iProp],coup4L -> Cp[bar[Fd], Fd, Ah][L][gt2,gt1,iProp],coup4R -> Cp[bar[Fd], Fd, Ah][R][gt2,gt1,iProp]},MP -> M[Ah][iProp],}
};