(* ----------------------------------------------------------------------------- *) 
(* This model was automatically created by SARAH version4.13.0  *) 
(* SARAH References: arXiv:0806.0538, 0909.2863, 1002.0840, 1207.0906, 1309.7223 *) 
(* (c) Florian Staub, 2013  *) 
(* ----------------------------------------------------------------------------- *) 
(* File created at 0:20 on 10.2.2021  *) 
(* ---------------------------------------------------------------------- *) 
 
 
LoopContributions[PengV2d2nu]={
(* Ah,Fd, Internal:bar[Fd], Propagator: VZ*) 
{{Ah,Fd, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mS1 -> M[Ah][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* hh,Fd, Internal:bar[Fd], Propagator: VZ*) 
{{hh,Fd, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mS1 -> M[hh][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* VZ,Fd, Internal:bar[Fd], Propagator: VZ*) 
{{VZ,Fd, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mV1 -> M[VZ],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* VZR,Fd, Internal:bar[Fd], Propagator: VZ*) 
{{VZR,Fd, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZR][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mV1 -> M[VZR],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* bar[Fu],Hpm, Internal:bar[Fd], Propagator: VZ*) 
{{bar[Fu],Hpm, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Fu, Hpm][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fu][i1],mS1 -> M[Hpm][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* bar[Fu],VWLm, Internal:bar[Fd], Propagator: VZ*) 
{{bar[Fu],VWLm, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fu][i1],mV1 -> M[VWLm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* bar[Fu],VWRm, Internal:bar[Fd], Propagator: VZ*) 
{{bar[Fu],VWRm, Internal->bar[Fd], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fu][i1],mV1 -> M[VWRm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZ]}},
(* Fd,Ah, Internal:Fd, Propagator: VZ*) 
{{Fd,Ah, Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fd][i1],mS1 -> M[Ah][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* Fd,hh, Internal:Fd, Propagator: VZ*) 
{{Fd,hh, Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fd][i1],mS1 -> M[hh][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* Fd,VZ, Internal:Fd, Propagator: VZ*) 
{{Fd,VZ, Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fd][i1],mV1 -> M[VZ],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* Fd,VZR, Internal:Fd, Propagator: VZ*) 
{{Fd,VZR, Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZR][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mF1 -> M[Fd][i1],mV1 -> M[VZR],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* Hpm,bar[Fu], Internal:Fd, Propagator: VZ*) 
{{Hpm,bar[Fu], Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,i3,i1],coup2R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i2,i1],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mS1 -> M[Hpm][i1],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* VWLm,bar[Fu], Internal:Fd, Propagator: VZ*) 
{{VWLm,bar[Fu], Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mV1 -> M[VWLm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* VWRm,bar[Fu], Internal:Fd, Propagator: VZ*) 
{{VWRm,bar[Fu], Internal->Fd, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},{mV1 -> M[VWRm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZ]}},
(* Ah,Fv, Internal:Fv, Propagator: VZ*) 
{{Ah,Fv, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, Ah][L][i3,i2,i1],coup2R -> Cp[Fv, Fv, Ah][R][i3,i2,i1],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mS1 -> M[Ah][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* Fe,Hpm, Internal:Fv, Propagator: VZ*) 
{{Fe,Hpm, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* Fe,VWLm, Internal:Fv, Propagator: VZ*) 
{{Fe,VWLm, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,i3],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fe][i1],mV1 -> M[VWLm],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* Fe,VWRm, Internal:Fv, Propagator: VZ*) 
{{Fe,VWRm, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,i3],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fe][i1],mV1 -> M[VWRm],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* Fv,hh, Internal:Fv, Propagator: VZ*) 
{{Fv,hh, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, hh][L][i3,i1,i2],coup2R -> Cp[Fv, Fv, hh][R][i3,i1,i2],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fv][i1],mS1 -> M[hh][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* Fv,VZ, Internal:Fv, Propagator: VZ*) 
{{Fv,VZ, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZ][L][i3,i1],coup2R -> Cp[Fv, Fv, VZ][R][i3,i1],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fv][i1],mV1 -> M[VZ],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* Fv,VZR, Internal:Fv, Propagator: VZ*) 
{{Fv,VZR, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZR][L][i3,i1],coup2R -> Cp[Fv, Fv, VZR][R][i3,i1],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fv][i1],mV1 -> M[VZR],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* Hpm,Fe, Internal:Fv, Propagator: VZ*) 
{{Hpm,Fe, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][i3,i2,i1],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* VWLm,Fe, Internal:Fv, Propagator: VZ*) 
{{VWLm,Fe, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][i3,i2],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mV1 -> M[VWLm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* VWRm,Fe, Internal:Fv, Propagator: VZ*) 
{{VWRm,Fe, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][i3,i2],coup3L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mV1 -> M[VWRm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZ]}},
(* Fv,Ah, Internal:Fv, Propagator: VZ*) 
{{Fv,Ah, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fv, Ah][L][i1,i3,i2],coup2R -> Cp[Fv, Fv, Ah][R][i1,i3,i2],coup1L -> Cp[Fv, Fv, Ah][L][gt4,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fv][i1],mS1 -> M[Ah][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* Hpm,Fe, Internal:Fv, Propagator: VZ*) 
{{Hpm,Fe, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][i3,i2,i1],coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt4,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt4,i1],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* VWLm,Fe, Internal:Fv, Propagator: VZ*) 
{{VWLm,Fe, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][i3,i2],coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt4],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt4],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mV1 -> M[VWLm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* VWRm,Fe, Internal:Fv, Propagator: VZ*) 
{{VWRm,Fe, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][i3,i2],coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt4],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt4],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mV1 -> M[VWRm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* hh,Fv, Internal:Fv, Propagator: VZ*) 
{{hh,Fv, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fv, hh][L][i2,i3,i1],coup2R -> Cp[Fv, Fv, hh][R][i2,i3,i1],coup1L -> Cp[Fv, Fv, hh][L][gt4,i2,i1],coup1R -> Cp[Fv, Fv, hh][R][gt4,i2,i1],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mS1 -> M[hh][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* VZ,Fv, Internal:Fv, Propagator: VZ*) 
{{VZ,Fv, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fv, VZ][L][i2,i3],coup2R -> Cp[Fv, Fv, VZ][R][i2,i3],coup1L -> Cp[Fv, Fv, VZ][L][gt4,i2],coup1R -> Cp[Fv, Fv, VZ][R][gt4,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mV1 -> M[VZ],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* VZR,Fv, Internal:Fv, Propagator: VZ*) 
{{VZR,Fv, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fv, VZR][L][i2,i3],coup2R -> Cp[Fv, Fv, VZR][R][i2,i3],coup1L -> Cp[Fv, Fv, VZR][L][gt4,i2],coup1R -> Cp[Fv, Fv, VZR][R][gt4,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mV1 -> M[VZR],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* Fe,Hpm, Internal:Fv, Propagator: VZ*) 
{{Fe,Hpm, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* Fe,VWLm, Internal:Fv, Propagator: VZ*) 
{{Fe,VWLm, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,i3],coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fe][i1],mV1 -> M[VWLm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}},
(* Fe,VWRm, Internal:Fv, Propagator: VZ*) 
{{Fe,VWRm, Internal->Fv, Propagator ->VZ},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,i3],coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},{mF1 -> M[Fe][i1],mV1 -> M[VWRm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZ]}}
(* Ah,Fd, Internal:bar[Fd], Propagator: VZR*) 
{{Ah,Fd, Internal->bar[Fd], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mS1 -> M[Ah][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZR]}},
(* hh,Fd, Internal:bar[Fd], Propagator: VZR*) 
{{hh,Fd, Internal->bar[Fd], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][i3,i2,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][i3,i2,i1],coup3L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mS1 -> M[hh][i1],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZR]}},
(* VZ,Fd, Internal:bar[Fd], Propagator: VZR*) 
{{VZ,Fd, Internal->bar[Fd], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mV1 -> M[VZ],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZR]}},
(* VZR,Fd, Internal:bar[Fd], Propagator: VZR*) 
{{VZR,Fd, Internal->bar[Fd], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][i3,i2],coup2R -> Cp[bar[Fd], Fd, VZR][R][i3,i2],coup3L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mV1 -> M[VZR],mF1 -> M[Fd][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZR]}},
(* bar[Fu],Hpm, Internal:bar[Fd], Propagator: VZR*) 
{{bar[Fu],Hpm, Internal->bar[Fd], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][i3,i1,i2],coup2R -> Cp[bar[Fd], Fu, Hpm][R][i3,i1,i2],coup3L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mF1 -> M[Fu][i1],mS1 -> M[Hpm][i2],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZR]}},
(* bar[Fu],VWLm, Internal:bar[Fd], Propagator: VZR*) 
{{bar[Fu],VWLm, Internal->bar[Fd], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mF1 -> M[Fu][i1],mV1 -> M[VWLm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZR]}},
(* bar[Fu],VWRm, Internal:bar[Fd], Propagator: VZR*) 
{{bar[Fu],VWRm, Internal->bar[Fd], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][i3,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][i3,i1],coup3L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup3R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mF1 -> M[Fu][i1],mV1 -> M[VWRm],MFin -> M[Fd][i3]-M[Fd][gt1],MP -> M[VZR]}},
(* Fd,Ah, Internal:Fd, Propagator: VZR*) 
{{Fd,Ah, Internal->Fd, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, Ah][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, Ah][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mF1 -> M[Fd][i1],mS1 -> M[Ah][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZR]}},
(* Fd,hh, Internal:Fd, Propagator: VZR*) 
{{Fd,hh, Internal->Fd, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][i1,i3,i2],coup2R -> Cp[bar[Fd], Fd, hh][R][i1,i3,i2],coup1L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mF1 -> M[Fd][i1],mS1 -> M[hh][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZR]}},
(* Fd,VZ, Internal:Fd, Propagator: VZR*) 
{{Fd,VZ, Internal->Fd, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mF1 -> M[Fd][i1],mV1 -> M[VZ],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZR]}},
(* Fd,VZR, Internal:Fd, Propagator: VZR*) 
{{Fd,VZR, Internal->Fd, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][i1,i3],coup2R -> Cp[bar[Fd], Fd, VZR][R][i1,i3],coup1L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup1R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mF1 -> M[Fd][i1],mV1 -> M[VZR],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZR]}},
(* Hpm,bar[Fu], Internal:Fd, Propagator: VZR*) 
{{Hpm,bar[Fu], Internal->Fd, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,i3,i1],coup2R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,i3,i1],coup1L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i2,i1],coup1R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i2,i1],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mS1 -> M[Hpm][i1],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZR]}},
(* VWLm,bar[Fu], Internal:Fd, Propagator: VZR*) 
{{VWLm,bar[Fu], Internal->Fd, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mV1 -> M[VWLm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZR]}},
(* VWRm,bar[Fu], Internal:Fd, Propagator: VZR*) 
{{VWRm,bar[Fu], Internal->Fd, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i3,gt1],coup3R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i3,gt1],coup2L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i2,i3],coup2R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i2,i3],coup1L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i2],coup1R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},{mV1 -> M[VWRm],mF1 -> M[Fu][i2],MFin -> M[Fd][i3]-M[Fd][gt2],MP -> M[VZR]}},
(* Ah,Fv, Internal:Fv, Propagator: VZR*) 
{{Ah,Fv, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, Ah][L][i3,i2,i1],coup2R -> Cp[Fv, Fv, Ah][R][i3,i2,i1],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mS1 -> M[Ah][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* Fe,Hpm, Internal:Fv, Propagator: VZR*) 
{{Fe,Hpm, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* Fe,VWLm, Internal:Fv, Propagator: VZR*) 
{{Fe,VWLm, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,i3],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fe][i1],mV1 -> M[VWLm],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* Fe,VWRm, Internal:Fv, Propagator: VZR*) 
{{Fe,VWRm, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,i3],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fe][i1],mV1 -> M[VWRm],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* Fv,hh, Internal:Fv, Propagator: VZR*) 
{{Fv,hh, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, hh][L][i3,i1,i2],coup2R -> Cp[Fv, Fv, hh][R][i3,i1,i2],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fv][i1],mS1 -> M[hh][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* Fv,VZ, Internal:Fv, Propagator: VZR*) 
{{Fv,VZ, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZ][L][i3,i1],coup2R -> Cp[Fv, Fv, VZ][R][i3,i1],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fv][i1],mV1 -> M[VZ],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* Fv,VZR, Internal:Fv, Propagator: VZR*) 
{{Fv,VZR, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, VZR][L][i3,i1],coup2R -> Cp[Fv, Fv, VZR][R][i3,i1],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fv][i1],mV1 -> M[VZR],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* Hpm,Fe, Internal:Fv, Propagator: VZR*) 
{{Hpm,Fe, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][i3,i2,i1],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* VWLm,Fe, Internal:Fv, Propagator: VZR*) 
{{VWLm,Fe, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][i3,i2],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mV1 -> M[VWLm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* VWRm,Fe, Internal:Fv, Propagator: VZR*) 
{{VWRm,Fe, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][i3,i2],coup3L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup3R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mV1 -> M[VWRm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt3],MP -> M[VZR]}},
(* Fv,Ah, Internal:Fv, Propagator: VZR*) 
{{Fv,Ah, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fv, Ah][L][i1,i3,i2],coup2R -> Cp[Fv, Fv, Ah][R][i1,i3,i2],coup1L -> Cp[Fv, Fv, Ah][L][gt4,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fv][i1],mS1 -> M[Ah][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* Hpm,Fe, Internal:Fv, Propagator: VZR*) 
{{Hpm,Fe, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][i3,i2,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][i3,i2,i1],coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt4,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt4,i1],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mS1 -> M[Hpm][i1],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* VWLm,Fe, Internal:Fv, Propagator: VZR*) 
{{VWLm,Fe, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][i3,i2],coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt4],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt4],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mV1 -> M[VWLm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* VWRm,Fe, Internal:Fv, Propagator: VZR*) 
{{VWRm,Fe, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][i3,i2],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][i3,i2],coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt4],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt4],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mV1 -> M[VWRm],mF1 -> M[Fe][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* hh,Fv, Internal:Fv, Propagator: VZR*) 
{{hh,Fv, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fv, hh][L][i2,i3,i1],coup2R -> Cp[Fv, Fv, hh][R][i2,i3,i1],coup1L -> Cp[Fv, Fv, hh][L][gt4,i2,i1],coup1R -> Cp[Fv, Fv, hh][R][gt4,i2,i1],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mS1 -> M[hh][i1],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* VZ,Fv, Internal:Fv, Propagator: VZR*) 
{{VZ,Fv, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fv, VZ][L][i2,i3],coup2R -> Cp[Fv, Fv, VZ][R][i2,i3],coup1L -> Cp[Fv, Fv, VZ][L][gt4,i2],coup1R -> Cp[Fv, Fv, VZ][R][gt4,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mV1 -> M[VZ],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* VZR,Fv, Internal:Fv, Propagator: VZR*) 
{{VZR,Fv, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[Fv, Fv, VZR][L][i2,i3],coup2R -> Cp[Fv, Fv, VZR][R][i2,i3],coup1L -> Cp[Fv, Fv, VZR][L][gt4,i2],coup1R -> Cp[Fv, Fv, VZR][R][gt4,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mV1 -> M[VZR],mF1 -> M[Fv][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* Fe,Hpm, Internal:Fv, Propagator: VZR*) 
{{Fe,Hpm, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,i3,i2],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,i3,i2],coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fe][i1],mS1 -> M[Hpm][i2],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* Fe,VWLm, Internal:Fv, Propagator: VZR*) 
{{Fe,VWLm, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,i3],coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fe][i1],mV1 -> M[VWLm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}},
(* Fe,VWRm, Internal:Fv, Propagator: VZR*) 
{{Fe,VWRm, Internal->Fv, Propagator ->VZR},chargefactor -> 1,{coup3L -> Cp[bar[Fe], Fv, VWRm][L][gt3,i3],coup3R -> Cp[bar[Fe], Fv, VWRm][R][gt3,i3],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,i3],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,i3],coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},{mF1 -> M[Fe][i1],mV1 -> M[VWRm],MFin -> M[Fv][i3]-M[Fv][gt4],MP -> M[VZR]}}
(* Ah,Fd,Fd, Propagator: VZ*) 
{{Ah,Fd,Fd, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* hh,Fd,Fd, Propagator: VZ*) 
{{hh,Fd,Fd, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* VZ,Fd,Fd, Propagator: VZ*) 
{{VZ,Fd,Fd, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* VZR,Fd,Fd, Propagator: VZ*) 
{{VZR,Fd,Fd, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, VZ][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZ][R][i3,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],hh,Ah, Propagator: VZ*) 
{{bar[Fd],hh,Ah, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZ][i3,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],Ah,hh, Propagator: VZ*) 
{{bar[Fd],Ah,hh, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZ][i2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],VZ,hh, Propagator: VZ*) 
{{bar[Fd],VZ,hh, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[hh, VZ, VZ][i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],VZR,hh, Propagator: VZ*) 
{{bar[Fd],VZR,hh, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[hh, VZ, VZR][i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],hh,VZ, Propagator: VZ*) 
{{bar[Fd],hh,VZ, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[hh, VZ, VZ][i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fd],hh,VZR, Propagator: VZ*) 
{{bar[Fd],hh,VZR, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup3 -> Cp[hh, VZ, VZR][i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],Hpm,Hpm, Propagator: VZ*) 
{{bar[Fu],Hpm,Hpm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[Hpm, conj[Hpm], VZ][i2,i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],VWLm,Hpm, Propagator: VZ*) 
{{bar[Fu],VWLm,Hpm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[conj[Hpm], VWLm, VZ][i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],VWRm,Hpm, Propagator: VZ*) 
{{bar[Fu],VWRm,Hpm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[conj[Hpm], VWRm, VZ][i3],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],Hpm,VWLm, Propagator: VZ*) 
{{bar[Fu],Hpm,VWLm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[Hpm, conj[VWLm], VZ][i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],VWLm,VWLm, Propagator: VZ*) 
{{bar[Fu],VWLm,VWLm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[conj[VWLm], VWLm, VZ],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],VWRm,VWLm, Propagator: VZ*) 
{{bar[Fu],VWRm,VWLm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[conj[VWLm], VWRm, VZ],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],Hpm,VWRm, Propagator: VZ*) 
{{bar[Fu],Hpm,VWRm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[Hpm, conj[VWRm], VZ][i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],VWLm,VWRm, Propagator: VZ*) 
{{bar[Fu],VWLm,VWRm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[conj[VWRm], VWLm, VZ],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* bar[Fu],VWRm,VWRm, Propagator: VZ*) 
{{bar[Fu],VWRm,VWRm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[conj[VWRm], VWRm, VZ],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* conj[Hpm],Fu,Fu, Propagator: VZ*) 
{{conj[Hpm],Fu,Fu, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,gt1,i1],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i3,i1],coup3L -> Cp[bar[Fu], Fu, VZ][L][i3,i2],coup3R -> Cp[bar[Fu], Fu, VZ][R][i3,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* conj[VWLm],Fu,Fu, Propagator: VZ*) 
{{conj[VWLm],Fu,Fu, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, VZ][L][i3,i2],coup3R -> Cp[bar[Fu], Fu, VZ][R][i3,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* conj[VWRm],Fu,Fu, Propagator: VZ*) 
{{conj[VWRm],Fu,Fu, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, VZ][L][i3,i2],coup3R -> Cp[bar[Fu], Fu, VZ][R][i3,i2],coup4L -> Cp[Fv, Fv, VZ][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZ][R][gt4,gt3]},MP -> M[VZ],},
(* Ah,Fv,Fv, Propagator: VZ*) 
{{Ah,Fv,Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i3,i1],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i3,i1],coup3L -> Cp[Fv, Fv, VZ][L][i3,i2],coup3R -> Cp[Fv, Fv, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,Hpm,Hpm, Propagator: VZ*) 
{{Fe,Hpm,Hpm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[Hpm, conj[Hpm], VZ][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,VWLm,Hpm, Propagator: VZ*) 
{{Fe,VWLm,Hpm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[conj[Hpm], VWLm, VZ][i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,VWRm,Hpm, Propagator: VZ*) 
{{Fe,VWRm,Hpm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[conj[Hpm], VWRm, VZ][i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,Hpm,VWLm, Propagator: VZ*) 
{{Fe,Hpm,VWLm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[Hpm, conj[VWLm], VZ][i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,VWLm,VWLm, Propagator: VZ*) 
{{Fe,VWLm,VWLm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[conj[VWLm], VWLm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,VWRm,VWLm, Propagator: VZ*) 
{{Fe,VWRm,VWLm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[conj[VWLm], VWRm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,Hpm,VWRm, Propagator: VZ*) 
{{Fe,Hpm,VWRm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[Hpm, conj[VWRm], VZ][i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,VWLm,VWRm, Propagator: VZ*) 
{{Fe,VWLm,VWRm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[conj[VWRm], VWLm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fe,VWRm,VWRm, Propagator: VZ*) 
{{Fe,VWRm,VWRm, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[conj[VWRm], VWRm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fv,hh,Ah, Propagator: VZ*) 
{{Fv,hh,Ah, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZ][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fv,Ah,hh, Propagator: VZ*) 
{{Fv,Ah,hh, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZ][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fv,VZ,hh, Propagator: VZ*) 
{{Fv,VZ,hh, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[hh, VZ, VZ][i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fv,VZR,hh, Propagator: VZ*) 
{{Fv,VZR,hh, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[hh, VZ, VZR][i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fv,hh,VZ, Propagator: VZ*) 
{{Fv,hh,VZ, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i1],coup3 -> Cp[hh, VZ, VZ][i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Fv,hh,VZR, Propagator: VZ*) 
{{Fv,hh,VZR, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i1],coup3 -> Cp[hh, VZ, VZR][i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* hh,Fv,Fv, Propagator: VZ*) 
{{hh,Fv,Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, hh][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i3,i1],coup2R -> Cp[Fv, Fv, hh][R][gt4,i3,i1],coup3L -> Cp[Fv, Fv, VZ][L][i3,i2],coup3R -> Cp[Fv, Fv, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* Hpm,Fe,Fe, Propagator: VZ*) 
{{Hpm,Fe,Fe, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i3,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i3,i1],coup3L -> Cp[bar[Fe], Fe, VZ][L][i3,i2],coup3R -> Cp[bar[Fe], Fe, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* VWLm,Fe,Fe, Propagator: VZ*) 
{{VWLm,Fe,Fe, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i3],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, VZ][L][i3,i2],coup3R -> Cp[bar[Fe], Fe, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* VWRm,Fe,Fe, Propagator: VZ*) 
{{VWRm,Fe,Fe, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i3],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, VZ][L][i3,i2],coup3R -> Cp[bar[Fe], Fe, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* VZ,Fv,Fv, Propagator: VZ*) 
{{VZ,Fv,Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i2],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i2],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup3L -> Cp[Fv, Fv, VZ][L][i3,i2],coup3R -> Cp[Fv, Fv, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* VZR,Fv,Fv, Propagator: VZ*) 
{{VZR,Fv,Fv, Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i2],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i2],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup3L -> Cp[Fv, Fv, VZ][L][i3,i2],coup3R -> Cp[Fv, Fv, VZ][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[Hpm],conj[Hpm], Propagator: VZ*) 
{{bar[Fe],conj[Hpm],conj[Hpm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Hpm, conj[Hpm], VZ][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[VWLm],conj[Hpm], Propagator: VZ*) 
{{bar[Fe],conj[VWLm],conj[Hpm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Hpm, conj[VWLm], VZ][i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[VWRm],conj[Hpm], Propagator: VZ*) 
{{bar[Fe],conj[VWRm],conj[Hpm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Hpm, conj[VWRm], VZ][i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[Hpm],conj[VWLm], Propagator: VZ*) 
{{bar[Fe],conj[Hpm],conj[VWLm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[conj[Hpm], VWLm, VZ][i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[VWLm],conj[VWLm], Propagator: VZ*) 
{{bar[Fe],conj[VWLm],conj[VWLm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[conj[VWLm], VWLm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[VWRm],conj[VWLm], Propagator: VZ*) 
{{bar[Fe],conj[VWRm],conj[VWLm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[conj[VWRm], VWLm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[Hpm],conj[VWRm], Propagator: VZ*) 
{{bar[Fe],conj[Hpm],conj[VWRm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[conj[Hpm], VWRm, VZ][i2],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[VWLm],conj[VWRm], Propagator: VZ*) 
{{bar[Fe],conj[VWLm],conj[VWRm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[conj[VWLm], VWRm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* bar[Fe],conj[VWRm],conj[VWRm], Propagator: VZ*) 
{{bar[Fe],conj[VWRm],conj[VWRm], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[conj[VWRm], VWRm, VZ],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* conj[Hpm],bar[Fe],bar[Fe], Propagator: VZ*) 
{{conj[Hpm],bar[Fe],bar[Fe], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i2,i1],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i2,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i3,gt4,i1],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i3,gt4,i1],coup3L -> Cp[bar[Fe], Fe, VZ][L][i2,i3],coup3R -> Cp[bar[Fe], Fe, VZ][R][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* conj[VWLm],bar[Fe],bar[Fe], Propagator: VZ*) 
{{conj[VWLm],bar[Fe],bar[Fe], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i2],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i2],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i3,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i3,gt4],coup3L -> Cp[bar[Fe], Fe, VZ][L][i2,i3],coup3R -> Cp[bar[Fe], Fe, VZ][R][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],},
(* conj[VWRm],bar[Fe],bar[Fe], Propagator: VZ*) 
{{conj[VWRm],bar[Fe],bar[Fe], Propagator ->VZ},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i2],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i2],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i3,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i3,gt4],coup3L -> Cp[bar[Fe], Fe, VZ][L][i2,i3],coup3R -> Cp[bar[Fe], Fe, VZ][R][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZ][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZ][R][gt2,gt1]},MP -> M[VZ],}
(* Ah,Fd,Fd, Propagator: VZR*) 
{{Ah,Fd,Fd, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, Ah][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, VZR][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZR][R][i3,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* hh,Fd,Fd, Propagator: VZR*) 
{{hh,Fd,Fd, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i2,gt1,i1],coup1R -> Cp[bar[Fd], Fd, hh][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i3,i1],coup3L -> Cp[bar[Fd], Fd, VZR][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZR][R][i3,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* VZ,Fd,Fd, Propagator: VZR*) 
{{VZ,Fd,Fd, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, VZR][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZR][R][i3,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* VZR,Fd,Fd, Propagator: VZR*) 
{{VZR,Fd,Fd, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i2,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i2,gt1],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i3],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i3],coup3L -> Cp[bar[Fd], Fd, VZR][L][i3,i2],coup3R -> Cp[bar[Fd], Fd, VZR][R][i3,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fd],hh,Ah, Propagator: VZR*) 
{{bar[Fd],hh,Ah, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, Ah][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, Ah][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZR][i3,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fd],Ah,hh, Propagator: VZR*) 
{{bar[Fd],Ah,hh, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, Ah][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, Ah][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[Ah, hh, VZR][i2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fd],VZ,hh, Propagator: VZR*) 
{{bar[Fd],VZ,hh, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZ][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZ][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[hh, VZ, VZR][i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fd],VZR,hh, Propagator: VZR*) 
{{bar[Fd],VZR,hh, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, VZR][L][i1,gt1],coup1R -> Cp[bar[Fd], Fd, VZR][R][i1,gt1],coup2L -> Cp[bar[Fd], Fd, hh][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fd, hh][R][gt2,i1,i3],coup3 -> Cp[hh, VZR, VZR][i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fd],hh,VZ, Propagator: VZR*) 
{{bar[Fd],hh,VZ, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZ][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZ][R][gt2,i1],coup3 -> Cp[hh, VZ, VZR][i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fd],hh,VZR, Propagator: VZR*) 
{{bar[Fd],hh,VZR, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fd], Fd, hh][L][i1,gt1,i2],coup1R -> Cp[bar[Fd], Fd, hh][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fd, VZR][L][gt2,i1],coup2R -> Cp[bar[Fd], Fd, VZR][R][gt2,i1],coup3 -> Cp[hh, VZR, VZR][i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],Hpm,Hpm, Propagator: VZR*) 
{{bar[Fu],Hpm,Hpm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[Hpm, conj[Hpm], VZR][i2,i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],VWLm,Hpm, Propagator: VZR*) 
{{bar[Fu],VWLm,Hpm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[conj[Hpm], VWLm, VZR][i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],VWRm,Hpm, Propagator: VZR*) 
{{bar[Fu],VWRm,Hpm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i1,i3],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i1,i3],coup3 -> Cp[conj[Hpm], VWRm, VZR][i3],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],Hpm,VWLm, Propagator: VZR*) 
{{bar[Fu],Hpm,VWLm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[Hpm, conj[VWLm], VZR][i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],VWLm,VWLm, Propagator: VZR*) 
{{bar[Fu],VWLm,VWLm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[conj[VWLm], VWLm, VZR],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],VWRm,VWLm, Propagator: VZR*) 
{{bar[Fu],VWRm,VWLm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i1],coup3 -> Cp[conj[VWLm], VWRm, VZR],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],Hpm,VWRm, Propagator: VZR*) 
{{bar[Fu],Hpm,VWRm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i1,gt1,i2],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i1,gt1,i2],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[Hpm, conj[VWRm], VZR][i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],VWLm,VWRm, Propagator: VZR*) 
{{bar[Fu],VWLm,VWRm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[conj[VWRm], VWLm, VZR],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* bar[Fu],VWRm,VWRm, Propagator: VZR*) 
{{bar[Fu],VWRm,VWRm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i1,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i1,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i1],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i1],coup3 -> Cp[conj[VWRm], VWRm, VZR],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* conj[Hpm],Fu,Fu, Propagator: VZR*) 
{{conj[Hpm],Fu,Fu, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[Hpm]][L][i2,gt1,i1],coup1R -> Cp[bar[Fu], Fd, conj[Hpm]][R][i2,gt1,i1],coup2L -> Cp[bar[Fd], Fu, Hpm][L][gt2,i3,i1],coup2R -> Cp[bar[Fd], Fu, Hpm][R][gt2,i3,i1],coup3L -> Cp[bar[Fu], Fu, VZR][L][i3,i2],coup3R -> Cp[bar[Fu], Fu, VZR][R][i3,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* conj[VWLm],Fu,Fu, Propagator: VZR*) 
{{conj[VWLm],Fu,Fu, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWLm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWLm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWLm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWLm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, VZR][L][i3,i2],coup3R -> Cp[bar[Fu], Fu, VZR][R][i3,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* conj[VWRm],Fu,Fu, Propagator: VZR*) 
{{conj[VWRm],Fu,Fu, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fu], Fd, conj[VWRm]][L][i2,gt1],coup1R -> Cp[bar[Fu], Fd, conj[VWRm]][R][i2,gt1],coup2L -> Cp[bar[Fd], Fu, VWRm][L][gt2,i3],coup2R -> Cp[bar[Fd], Fu, VWRm][R][gt2,i3],coup3L -> Cp[bar[Fu], Fu, VZR][L][i3,i2],coup3R -> Cp[bar[Fu], Fu, VZR][R][i3,i2],coup4L -> Cp[Fv, Fv, VZR][L][gt4,gt3],coup4R -> Cp[Fv, Fv, VZR][R][gt4,gt3]},MP -> M[VZR],},
(* Ah,Fv,Fv, Propagator: VZR*) 
{{Ah,Fv,Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i3,i1],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i3,i1],coup3L -> Cp[Fv, Fv, VZR][L][i3,i2],coup3R -> Cp[Fv, Fv, VZR][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,Hpm,Hpm, Propagator: VZR*) 
{{Fe,Hpm,Hpm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[Hpm, conj[Hpm], VZR][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,VWLm,Hpm, Propagator: VZR*) 
{{Fe,VWLm,Hpm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[conj[Hpm], VWLm, VZR][i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,VWRm,Hpm, Propagator: VZR*) 
{{Fe,VWRm,Hpm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt4,i3],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt4,i3],coup3 -> Cp[conj[Hpm], VWRm, VZR][i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,Hpm,VWLm, Propagator: VZR*) 
{{Fe,Hpm,VWLm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[Hpm, conj[VWLm], VZR][i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,VWLm,VWLm, Propagator: VZR*) 
{{Fe,VWLm,VWLm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[conj[VWLm], VWLm, VZR],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,VWRm,VWLm, Propagator: VZR*) 
{{Fe,VWRm,VWLm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt4],coup3 -> Cp[conj[VWLm], VWRm, VZR],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,Hpm,VWRm, Propagator: VZR*) 
{{Fe,Hpm,VWRm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i1,i2],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i1,i2],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[Hpm, conj[VWRm], VZR][i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,VWLm,VWRm, Propagator: VZR*) 
{{Fe,VWLm,VWRm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[conj[VWRm], VWLm, VZR],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fe,VWRm,VWRm, Propagator: VZR*) 
{{Fe,VWRm,VWRm, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i1],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i1],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt4],coup3 -> Cp[conj[VWRm], VWRm, VZR],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fv,hh,Ah, Propagator: VZR*) 
{{Fv,hh,Ah, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, Ah][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, Ah][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZR][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fv,Ah,hh, Propagator: VZR*) 
{{Fv,Ah,hh, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, Ah][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, Ah][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[Ah, hh, VZR][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fv,VZ,hh, Propagator: VZR*) 
{{Fv,VZ,hh, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[hh, VZ, VZR][i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fv,VZR,hh, Propagator: VZR*) 
{{Fv,VZR,hh, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i1],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i1,i3],coup2R -> Cp[Fv, Fv, hh][R][gt4,i1,i3],coup3 -> Cp[hh, VZR, VZR][i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fv,hh,VZ, Propagator: VZR*) 
{{Fv,hh,VZ, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i1],coup3 -> Cp[hh, VZ, VZR][i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Fv,hh,VZR, Propagator: VZR*) 
{{Fv,hh,VZR, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i1,i2],coup1R -> Cp[Fv, Fv, hh][R][gt3,i1,i2],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i1],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i1],coup3 -> Cp[hh, VZR, VZR][i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* hh,Fv,Fv, Propagator: VZR*) 
{{hh,Fv,Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, hh][L][gt3,i2,i1],coup1R -> Cp[Fv, Fv, hh][R][gt3,i2,i1],coup2L -> Cp[Fv, Fv, hh][L][gt4,i3,i1],coup2R -> Cp[Fv, Fv, hh][R][gt4,i3,i1],coup3L -> Cp[Fv, Fv, VZR][L][i3,i2],coup3R -> Cp[Fv, Fv, VZR][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* Hpm,Fe,Fe, Propagator: VZR*) 
{{Hpm,Fe,Fe, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i2,gt3,i1],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i2,gt3,i1],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i3,i1],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i3,i1],coup3L -> Cp[bar[Fe], Fe, VZR][L][i3,i2],coup3R -> Cp[bar[Fe], Fe, VZR][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* VWLm,Fe,Fe, Propagator: VZR*) 
{{VWLm,Fe,Fe, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i3],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, VZR][L][i3,i2],coup3R -> Cp[bar[Fe], Fe, VZR][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* VWRm,Fe,Fe, Propagator: VZR*) 
{{VWRm,Fe,Fe, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i2,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i2,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i3],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i3],coup3L -> Cp[bar[Fe], Fe, VZR][L][i3,i2],coup3R -> Cp[bar[Fe], Fe, VZR][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* VZ,Fv,Fv, Propagator: VZR*) 
{{VZ,Fv,Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZ][L][gt3,i2],coup1R -> Cp[Fv, Fv, VZ][R][gt3,i2],coup2L -> Cp[Fv, Fv, VZ][L][gt4,i3],coup2R -> Cp[Fv, Fv, VZ][R][gt4,i3],coup3L -> Cp[Fv, Fv, VZR][L][i3,i2],coup3R -> Cp[Fv, Fv, VZR][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* VZR,Fv,Fv, Propagator: VZR*) 
{{VZR,Fv,Fv, Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fv, VZR][L][gt3,i2],coup1R -> Cp[Fv, Fv, VZR][R][gt3,i2],coup2L -> Cp[Fv, Fv, VZR][L][gt4,i3],coup2R -> Cp[Fv, Fv, VZR][R][gt4,i3],coup3L -> Cp[Fv, Fv, VZR][L][i3,i2],coup3R -> Cp[Fv, Fv, VZR][R][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[Hpm],conj[Hpm], Propagator: VZR*) 
{{bar[Fe],conj[Hpm],conj[Hpm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Hpm, conj[Hpm], VZR][i3,i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[VWLm],conj[Hpm], Propagator: VZR*) 
{{bar[Fe],conj[VWLm],conj[Hpm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Hpm, conj[VWLm], VZR][i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[VWRm],conj[Hpm], Propagator: VZR*) 
{{bar[Fe],conj[VWRm],conj[Hpm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[Hpm]][L][gt4,i1,i3],coup2R -> Cp[Fv, Fe, conj[Hpm]][R][gt4,i1,i3],coup3 -> Cp[Hpm, conj[VWRm], VZR][i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[Hpm],conj[VWLm], Propagator: VZR*) 
{{bar[Fe],conj[Hpm],conj[VWLm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[conj[Hpm], VWLm, VZR][i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[VWLm],conj[VWLm], Propagator: VZR*) 
{{bar[Fe],conj[VWLm],conj[VWLm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[conj[VWLm], VWLm, VZR],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[VWRm],conj[VWLm], Propagator: VZR*) 
{{bar[Fe],conj[VWRm],conj[VWLm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWLm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWLm]][R][gt4,i1],coup3 -> Cp[conj[VWRm], VWLm, VZR],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[Hpm],conj[VWRm], Propagator: VZR*) 
{{bar[Fe],conj[Hpm],conj[VWRm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, Hpm][L][i1,gt3,i2],coup1R -> Cp[bar[Fe], Fv, Hpm][R][i1,gt3,i2],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[conj[Hpm], VWRm, VZR][i2],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[VWLm],conj[VWRm], Propagator: VZR*) 
{{bar[Fe],conj[VWLm],conj[VWRm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWLm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWLm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[conj[VWLm], VWRm, VZR],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* bar[Fe],conj[VWRm],conj[VWRm], Propagator: VZR*) 
{{bar[Fe],conj[VWRm],conj[VWRm], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[bar[Fe], Fv, VWRm][L][i1,gt3],coup1R -> Cp[bar[Fe], Fv, VWRm][R][i1,gt3],coup2L -> Cp[Fv, Fe, conj[VWRm]][L][gt4,i1],coup2R -> Cp[Fv, Fe, conj[VWRm]][R][gt4,i1],coup3 -> Cp[conj[VWRm], VWRm, VZR],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* conj[Hpm],bar[Fe],bar[Fe], Propagator: VZR*) 
{{conj[Hpm],bar[Fe],bar[Fe], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[Hpm]][L][gt3,i2,i1],coup1R -> Cp[Fv, Fe, conj[Hpm]][R][gt3,i2,i1],coup2L -> Cp[bar[Fe], Fv, Hpm][L][i3,gt4,i1],coup2R -> Cp[bar[Fe], Fv, Hpm][R][i3,gt4,i1],coup3L -> Cp[bar[Fe], Fe, VZR][L][i2,i3],coup3R -> Cp[bar[Fe], Fe, VZR][R][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* conj[VWLm],bar[Fe],bar[Fe], Propagator: VZR*) 
{{conj[VWLm],bar[Fe],bar[Fe], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWLm]][L][gt3,i2],coup1R -> Cp[Fv, Fe, conj[VWLm]][R][gt3,i2],coup2L -> Cp[bar[Fe], Fv, VWLm][L][i3,gt4],coup2R -> Cp[bar[Fe], Fv, VWLm][R][i3,gt4],coup3L -> Cp[bar[Fe], Fe, VZR][L][i2,i3],coup3R -> Cp[bar[Fe], Fe, VZR][R][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],},
(* conj[VWRm],bar[Fe],bar[Fe], Propagator: VZR*) 
{{conj[VWRm],bar[Fe],bar[Fe], Propagator ->VZR},chargefactor -> 1,{coup1L -> Cp[Fv, Fe, conj[VWRm]][L][gt3,i2],coup1R -> Cp[Fv, Fe, conj[VWRm]][R][gt3,i2],coup2L -> Cp[bar[Fe], Fv, VWRm][L][i3,gt4],coup2R -> Cp[bar[Fe], Fv, VWRm][R][i3,gt4],coup3L -> Cp[bar[Fe], Fe, VZR][L][i2,i3],coup3R -> Cp[bar[Fe], Fe, VZR][R][i2,i3],coup4L -> Cp[bar[Fd], Fd, VZR][L][gt2,gt1],coup4R -> Cp[bar[Fd], Fd, VZR][R][gt2,gt1]},MP -> M[VZR],}
};