{{{Ah, Ah, Cp[Uhh[{gO1}], Ah[{gI1}], Ah[{gI2}]], SSS, 1, 1/4}, 
  {VP, Ah, Cp[Uhh[{gO1}], VP, Ah[{gI2}]], SSV, 1, 1/2}, 
  {VZ, Ah, Cp[Uhh[{gO1}], VZ, Ah[{gI2}]], SSV, 1, 1/2}, 
  {VZR, Ah, Cp[Uhh[{gO1}], VZR, Ah[{gI2}]], SSV, 1, 1/2}, 
  {bar[Fd], Fd, Cp[Uhh[{gO1}], bar[Fd[{gI1}]], Fd[{gI2}]], FFS, 3, 1/2}, 
  {bar[Fe], Fe, Cp[Uhh[{gO1}], bar[Fe[{gI1}]], Fe[{gI2}]], FFS, 1, 1/2}, 
  {bar[Fu], Fu, Cp[Uhh[{gO1}], bar[Fu[{gI1}]], Fu[{gI2}]], FFS, 3, 1/2}, 
  {Fv, Fv, Cp[Uhh[{gO1}], Fv[{gI1}], Fv[{gI2}]], FFS, 1, 1/4}, 
  {bar[gWLm], gWLm, Cp[Uhh[{gO1}], bar[gWLm], gWLm], GGS, 1, 1/2}, 
  {bar[gWRm], gWLm, Cp[Uhh[{gO1}], bar[gWRm], gWLm], GGS, 1, 1}, 
  {bar[gWLmC], gWLmC, Cp[Uhh[{gO1}], bar[gWLmC], gWLmC], GGS, 1, 1/2}, 
  {bar[gWRmC], gWLmC, Cp[Uhh[{gO1}], bar[gWRmC], gWLmC], GGS, 1, 1}, 
  {bar[gWRm], gWRm, Cp[Uhh[{gO1}], bar[gWRm], gWRm], GGS, 1, 1/2}, 
  {bar[gWRmC], gWRmC, Cp[Uhh[{gO1}], bar[gWRmC], gWRmC], GGS, 1, 1/2}, 
  {bar[gZ], gZ, Cp[Uhh[{gO1}], bar[gZ], gZ], GGS, 1, 1/2}, 
  {bar[gZR], gZ, Cp[Uhh[{gO1}], bar[gZR], gZ], GGS, 1, 1}, 
  {bar[gZR], gZR, Cp[Uhh[{gO1}], bar[gZR], gZR], GGS, 1, 1/2}, 
  {hh, hh, Cp[Uhh[{gO1}], hh[{gI1}], hh[{gI2}]], SSS, 1, 1/4}, 
  {conj[Hpm], Hpm, Cp[Uhh[{gO1}], conj[Hpm[{gI1}]], Hpm[{gI2}]], SSS, 1, 
   1/2}, {conj[VWLm], Hpm, Cp[Uhh[{gO1}], conj[VWLm], Hpm[{gI2}]], SSV, 1, 
   1}, {conj[VWRm], Hpm, Cp[Uhh[{gO1}], conj[VWRm], Hpm[{gI2}]], SSV, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[Uhh[{gO1}], conj[Hppmm[{gI1}]], Hppmm[{gI2}]], SSS, 
   1, 1/2}, {VZ, VP, Cp[Uhh[{gO1}], VZ, VP], SVV, 1, 1/2}, 
  {VZR, VP, Cp[Uhh[{gO1}], VZR, VP], SVV, 1, 1/2}, 
  {conj[VWLm], VWLm, Cp[Uhh[{gO1}], conj[VWLm], VWLm], SVV, 1, 1/2}, 
  {conj[VWRm], VWLm, Cp[Uhh[{gO1}], conj[VWRm], VWLm], SVV, 1, 1}, 
  {conj[VWRm], VWRm, Cp[Uhh[{gO1}], conj[VWRm], VWRm], SVV, 1, 1/2}, 
  {VZ, VZ, Cp[Uhh[{gO1}], VZ, VZ], SVV, 1, 1/4}, 
  {VZR, VZ, Cp[Uhh[{gO1}], VZR, VZ], SVV, 1, 1/2}, 
  {VZR, VZR, Cp[Uhh[{gO1}], VZR, VZR], SVV, 1, 1/4}, 
  {Ah, Ah, Cp[Uhh[{gO1}], Uhh[{gO1}], Ah[{gI1}], Ah[{gI1}]], SSSS, 1, 1/2}, 
  {hh, hh, Cp[Uhh[{gO1}], Uhh[{gO1}], hh[{gI1}], hh[{gI1}]], SSSS, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[Uhh[{gO1}], Uhh[{gO1}], conj[Hpm[{gI1}]], Hpm[{gI1}]], 
   SSSS, 1, 1}, {conj[Hppmm], Hppmm, Cp[Uhh[{gO1}], Uhh[{gO1}], 
    conj[Hppmm[{gI1}]], Hppmm[{gI1}]], SSSS, 1, 1}, 
  {VP, VP, Cp[Uhh[{gO1}], Uhh[{gO1}], VP, VP], SSVV, 1, 1/2}, 
  {conj[VWLm], VWLm, Cp[Uhh[{gO1}], Uhh[{gO1}], conj[VWLm], VWLm], SSVV, 1, 
   1}, {conj[VWRm], VWRm, Cp[Uhh[{gO1}], Uhh[{gO1}], conj[VWRm], VWRm], SSVV, 
   1, 1}, {VZ, VZ, Cp[Uhh[{gO1}], Uhh[{gO1}], VZ, VZ], SSVV, 1, 1/2}, 
  {VZR, VZR, Cp[Uhh[{gO1}], Uhh[{gO1}], VZR, VZR], SSVV, 1, 1/2}}, 
 {{hh, Ah, Cp[UAh[{gO1}], hh[{gI1}], Ah[{gI2}]], SSS, 1, 1/2}, 
  {bar[Fd], Fd, Cp[UAh[{gO1}], bar[Fd[{gI1}]], Fd[{gI2}]], FFS, 3, 1/2}, 
  {bar[Fe], Fe, Cp[UAh[{gO1}], bar[Fe[{gI1}]], Fe[{gI2}]], FFS, 1, 1/2}, 
  {bar[Fu], Fu, Cp[UAh[{gO1}], bar[Fu[{gI1}]], Fu[{gI2}]], FFS, 3, 1/2}, 
  {Fv, Fv, Cp[UAh[{gO1}], Fv[{gI1}], Fv[{gI2}]], FFS, 1, 1/4}, 
  {bar[gWLm], gWLm, Cp[UAh[{gO1}], bar[gWLm], gWLm], GGS, 1, 1/2}, 
  {bar[gWRm], gWLm, Cp[UAh[{gO1}], bar[gWRm], gWLm], GGS, 1, 1}, 
  {bar[gWLmC], gWLmC, Cp[UAh[{gO1}], bar[gWLmC], gWLmC], GGS, 1, 1/2}, 
  {bar[gWRmC], gWLmC, Cp[UAh[{gO1}], bar[gWRmC], gWLmC], GGS, 1, 1}, 
  {bar[gWRm], gWRm, Cp[UAh[{gO1}], bar[gWRm], gWRm], GGS, 1, 1/2}, 
  {bar[gWRmC], gWRmC, Cp[UAh[{gO1}], bar[gWRmC], gWRmC], GGS, 1, 1/2}, 
  {VP, hh, Cp[UAh[{gO1}], VP, hh[{gI2}]], SSV, 1, 1/2}, 
  {VZ, hh, Cp[UAh[{gO1}], VZ, hh[{gI2}]], SSV, 1, 1/2}, 
  {VZR, hh, Cp[UAh[{gO1}], VZR, hh[{gI2}]], SSV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[UAh[{gO1}], conj[Hpm[{gI1}]], Hpm[{gI2}]], SSS, 1, 
   1/2}, {conj[VWLm], Hpm, Cp[UAh[{gO1}], conj[VWLm], Hpm[{gI2}]], SSV, 1, 
   1}, {conj[VWRm], Hpm, Cp[UAh[{gO1}], conj[VWRm], Hpm[{gI2}]], SSV, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[UAh[{gO1}], conj[Hppmm[{gI1}]], Hppmm[{gI2}]], SSS, 
   1, 1/2}, {conj[VWRm], VWLm, Cp[UAh[{gO1}], conj[VWRm], VWLm], SVV, 1, 1}, 
  {Ah, Ah, Cp[UAh[{gO1}], UAh[{gO1}], Ah[{gI1}], Ah[{gI1}]], SSSS, 1, 1/2}, 
  {hh, hh, Cp[UAh[{gO1}], UAh[{gO1}], hh[{gI1}], hh[{gI1}]], SSSS, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[UAh[{gO1}], UAh[{gO1}], conj[Hpm[{gI1}]], Hpm[{gI1}]], 
   SSSS, 1, 1}, {conj[Hppmm], Hppmm, Cp[UAh[{gO1}], UAh[{gO1}], 
    conj[Hppmm[{gI1}]], Hppmm[{gI1}]], SSSS, 1, 1}, 
  {VP, VP, Cp[UAh[{gO1}], UAh[{gO1}], VP, VP], SSVV, 1, 1/2}, 
  {conj[VWLm], VWLm, Cp[UAh[{gO1}], UAh[{gO1}], conj[VWLm], VWLm], SSVV, 1, 
   1}, {conj[VWRm], VWRm, Cp[UAh[{gO1}], UAh[{gO1}], conj[VWRm], VWRm], SSVV, 
   1, 1}, {VZ, VZ, Cp[UAh[{gO1}], UAh[{gO1}], VZ, VZ], SSVV, 1, 1/2}, 
  {VZR, VZR, Cp[UAh[{gO1}], UAh[{gO1}], VZR, VZR], SSVV, 1, 1/2}}, 
 {{Hpm, Ah, Cp[conj[UHpm[{gO1}]], Hpm[{gI1}], Ah[{gI2}]], SSS, 1, 1}, 
  {VWLm, Ah, Cp[conj[UHpm[{gO1}]], VWLm, Ah[{gI2}]], SSV, 1, 1}, 
  {VWRm, Ah, Cp[conj[UHpm[{gO1}]], VWRm, Ah[{gI2}]], SSV, 1, 1}, 
  {bar[Fu], Fd, Cp[conj[UHpm[{gO1}]], bar[Fu[{gI1}]], Fd[{gI2}]], FFS, 3, 1}, 
  {Fv, Fe, Cp[conj[UHpm[{gO1}]], Fv[{gI1}], Fe[{gI2}]], FFS, 1, 1}, 
  {bar[gZ], gWLm, Cp[conj[UHpm[{gO1}]], bar[gZ], gWLm], GGS, 1, 1}, 
  {bar[gZR], gWLm, Cp[conj[UHpm[{gO1}]], bar[gZR], gWLm], GGS, 1, 1}, 
  {bar[gZ], gWRm, Cp[conj[UHpm[{gO1}]], bar[gZ], gWRm], GGS, 1, 1}, 
  {bar[gZR], gWRm, Cp[conj[UHpm[{gO1}]], bar[gZR], gWRm], GGS, 1, 1}, 
  {bar[gWLmC], gZ, Cp[conj[UHpm[{gO1}]], bar[gWLmC], gZ], GGS, 1, 1}, 
  {bar[gWRmC], gZ, Cp[conj[UHpm[{gO1}]], bar[gWRmC], gZ], GGS, 1, 1}, 
  {bar[gWLmC], gZR, Cp[conj[UHpm[{gO1}]], bar[gWLmC], gZR], GGS, 1, 1}, 
  {bar[gWRmC], gZR, Cp[conj[UHpm[{gO1}]], bar[gWRmC], gZR], GGS, 1, 1}, 
  {Hpm, hh, Cp[conj[UHpm[{gO1}]], Hpm[{gI1}], hh[{gI2}]], SSS, 1, 1}, 
  {VWLm, hh, Cp[conj[UHpm[{gO1}]], VWLm, hh[{gI2}]], SSV, 1, 1}, 
  {VWRm, hh, Cp[conj[UHpm[{gO1}]], VWRm, hh[{gI2}]], SSV, 1, 1}, 
  {VP, Hpm, Cp[conj[UHpm[{gO1}]], VP, Hpm[{gI2}]], SSV, 1, 1}, 
  {VZ, Hpm, Cp[conj[UHpm[{gO1}]], VZ, Hpm[{gI2}]], SSV, 1, 1}, 
  {VZR, Hpm, Cp[conj[UHpm[{gO1}]], VZR, Hpm[{gI2}]], SSV, 1, 1}, 
  {conj[Hpm], Hppmm, Cp[conj[UHpm[{gO1}]], conj[Hpm[{gI1}]], Hppmm[{gI2}]], 
   SSS, 1, 1}, {conj[VWLm], Hppmm, Cp[conj[UHpm[{gO1}]], conj[VWLm], 
    Hppmm[{gI2}]], SSV, 1, 1}, {conj[VWRm], Hppmm, 
   Cp[conj[UHpm[{gO1}]], conj[VWRm], Hppmm[{gI2}]], SSV, 1, 1}, 
  {VWLm, VP, Cp[conj[UHpm[{gO1}]], VWLm, VP], SVV, 1, 1}, 
  {VWRm, VP, Cp[conj[UHpm[{gO1}]], VWRm, VP], SVV, 1, 1}, 
  {VZ, VWLm, Cp[conj[UHpm[{gO1}]], VZ, VWLm], SVV, 1, 1}, 
  {VZR, VWLm, Cp[conj[UHpm[{gO1}]], VZR, VWLm], SVV, 1, 1}, 
  {VZ, VWRm, Cp[conj[UHpm[{gO1}]], VZ, VWRm], SVV, 1, 1}, 
  {VZR, VWRm, Cp[conj[UHpm[{gO1}]], VZR, VWRm], SVV, 1, 1}, 
  {Ah, Ah, Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], Ah[{gI1}], Ah[{gI1}]], SSSS, 1, 
   1/2}, {hh, hh, Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], hh[{gI1}], hh[{gI1}]], 
   SSSS, 1, 1/2}, {conj[Hpm], Hpm, Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], 
    conj[Hpm[{gI1}]], Hpm[{gI1}]], SSSS, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], conj[Hppmm[{gI1}]], 
    Hppmm[{gI1}]], SSSS, 1, 1}, {VP, VP, Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], 
    VP, VP], SSVV, 1, 1/2}, {conj[VWLm], VWLm, 
   Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], conj[VWLm], VWLm], SSVV, 1, 1}, 
  {conj[VWRm], VWRm, Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], conj[VWRm], VWRm], 
   SSVV, 1, 1}, {VZ, VZ, Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], VZ, VZ], SSVV, 1, 
   1/2}, {VZR, VZR, Cp[UHpm[{gO1}], conj[UHpm[{gO1}]], VZR, VZR], SSVV, 1, 
   1/2}}, {{Hppmm, Ah, Cp[conj[UHppmm[{gO1}]], Hppmm[{gI1}], Ah[{gI2}]], SSS, 
   1, 1}, {Fe, Fe, Cp[conj[UHppmm[{gO1}]], Fe[{gI1}], Fe[{gI2}]], FFS, 1, 
   1/2}, {bar[gWLmC], gWLm, Cp[conj[UHppmm[{gO1}]], bar[gWLmC], gWLm], GGS, 
   1, 1}, {bar[gWRmC], gWLm, Cp[conj[UHppmm[{gO1}]], bar[gWRmC], gWLm], GGS, 
   1, 1}, {bar[gWLmC], gWRm, Cp[conj[UHppmm[{gO1}]], bar[gWLmC], gWRm], GGS, 
   1, 1}, {bar[gWRmC], gWRm, Cp[conj[UHppmm[{gO1}]], bar[gWRmC], gWRm], GGS, 
   1, 1}, {Hppmm, hh, Cp[conj[UHppmm[{gO1}]], Hppmm[{gI1}], hh[{gI2}]], SSS, 
   1, 1}, {Hpm, Hpm, Cp[conj[UHppmm[{gO1}]], Hpm[{gI1}], Hpm[{gI2}]], SSS, 1, 
   1/2}, {VWLm, Hpm, Cp[conj[UHppmm[{gO1}]], VWLm, Hpm[{gI2}]], SSV, 1, 1}, 
  {VWRm, Hpm, Cp[conj[UHppmm[{gO1}]], VWRm, Hpm[{gI2}]], SSV, 1, 1}, 
  {VP, Hppmm, Cp[conj[UHppmm[{gO1}]], VP, Hppmm[{gI2}]], SSV, 1, 1}, 
  {VZ, Hppmm, Cp[conj[UHppmm[{gO1}]], VZ, Hppmm[{gI2}]], SSV, 1, 1}, 
  {VZR, Hppmm, Cp[conj[UHppmm[{gO1}]], VZR, Hppmm[{gI2}]], SSV, 1, 1}, 
  {VWLm, VWLm, Cp[conj[UHppmm[{gO1}]], VWLm, VWLm], SVV, 1, 1/2}, 
  {VWRm, VWLm, Cp[conj[UHppmm[{gO1}]], VWRm, VWLm], SVV, 1, 1}, 
  {VWRm, VWRm, Cp[conj[UHppmm[{gO1}]], VWRm, VWRm], SVV, 1, 1/2}, 
  {Ah, Ah, Cp[UHppmm[{gO1}], conj[UHppmm[{gO1}]], Ah[{gI1}], Ah[{gI1}]], 
   SSSS, 1, 1/2}, {hh, hh, Cp[UHppmm[{gO1}], conj[UHppmm[{gO1}]], hh[{gI1}], 
    hh[{gI1}]], SSSS, 1, 1/2}, {conj[Hpm], Hpm, 
   Cp[UHppmm[{gO1}], conj[UHppmm[{gO1}]], conj[Hpm[{gI1}]], Hpm[{gI1}]], 
   SSSS, 1, 1}, {conj[Hppmm], Hppmm, Cp[UHppmm[{gO1}], conj[UHppmm[{gO1}]], 
    conj[Hppmm[{gI1}]], Hppmm[{gI1}]], SSSS, 1, 1}, 
  {VP, VP, Cp[UHppmm[{gO1}], conj[UHppmm[{gO1}]], VP, VP], SSVV, 1, 1/2}, 
  {conj[VWLm], VWLm, Cp[UHppmm[{gO1}], conj[UHppmm[{gO1}]], conj[VWLm], 
    VWLm], SSVV, 1, 1}, {conj[VWRm], VWRm, Cp[UHppmm[{gO1}], 
    conj[UHppmm[{gO1}]], conj[VWRm], VWRm], SSVV, 1, 1}, 
  {VZ, VZ, Cp[UHppmm[{gO1}], conj[UHppmm[{gO1}]], VZ, VZ], SSVV, 1, 1/2}, 
  {VZR, VZR, Cp[UHppmm[{gO1}], conj[UHppmm[{gO1}]], VZR, VZR], SSVV, 1, 
   1/2}}, {{Fd, Ah, Cp[bar[UFd[{gO1}]], Fd[{gI1}], Ah[{gI2}]], FFS, 1, 1}, 
  {hh, Fd, Cp[bar[UFd[{gO1}]], hh[{gI1}], Fd[{gI2}]], FFS, 1, 1}, 
  {VG, Fd, Cp[bar[UFd[{gO1}]], VG, Fd[{gI2}]], FFV, 4/3, 1}, 
  {VP, Fd, Cp[bar[UFd[{gO1}]], VP, Fd[{gI2}]], FFV, 1, 1}, 
  {VZ, Fd, Cp[bar[UFd[{gO1}]], VZ, Fd[{gI2}]], FFV, 1, 1}, 
  {VZR, Fd, Cp[bar[UFd[{gO1}]], VZR, Fd[{gI2}]], FFV, 1, 1}, 
  {Hpm, Fu, Cp[bar[UFd[{gO1}]], Hpm[{gI1}], Fu[{gI2}]], FFS, 1, 1}, 
  {VWLm, Fu, Cp[bar[UFd[{gO1}]], VWLm, Fu[{gI2}]], FFV, 1, 1}, 
  {VWRm, Fu, Cp[bar[UFd[{gO1}]], VWRm, Fu[{gI2}]], FFV, 1, 1}}, 
 {{Fu, Ah, Cp[bar[UFu[{gO1}]], Fu[{gI1}], Ah[{gI2}]], FFS, 1, 1}, 
  {conj[Hpm], Fd, Cp[bar[UFu[{gO1}]], conj[Hpm[{gI1}]], Fd[{gI2}]], FFS, 1, 
   1}, {conj[VWLm], Fd, Cp[bar[UFu[{gO1}]], conj[VWLm], Fd[{gI2}]], FFV, 1, 
   1}, {conj[VWRm], Fd, Cp[bar[UFu[{gO1}]], conj[VWRm], Fd[{gI2}]], FFV, 1, 
   1}, {hh, Fu, Cp[bar[UFu[{gO1}]], hh[{gI1}], Fu[{gI2}]], FFS, 1, 1}, 
  {VG, Fu, Cp[bar[UFu[{gO1}]], VG, Fu[{gI2}]], FFV, 4/3, 1}, 
  {VP, Fu, Cp[bar[UFu[{gO1}]], VP, Fu[{gI2}]], FFV, 1, 1}, 
  {VZ, Fu, Cp[bar[UFu[{gO1}]], VZ, Fu[{gI2}]], FFV, 1, 1}, 
  {VZR, Fu, Cp[bar[UFu[{gO1}]], VZR, Fu[{gI2}]], FFV, 1, 1}}, 
 {{Fe, Ah, Cp[bar[UFe[{gO1}]], Fe[{gI1}], Ah[{gI2}]], FFS, 1, 1}, 
  {hh, Fe, Cp[bar[UFe[{gO1}]], hh[{gI1}], Fe[{gI2}]], FFS, 1, 1}, 
  {VP, Fe, Cp[bar[UFe[{gO1}]], VP, Fe[{gI2}]], FFV, 1, 1}, 
  {VZ, Fe, Cp[bar[UFe[{gO1}]], VZ, Fe[{gI2}]], FFV, 1, 1}, 
  {VZR, Fe, Cp[bar[UFe[{gO1}]], VZR, Fe[{gI2}]], FFV, 1, 1}, 
  {Hpm, Fv, Cp[bar[UFe[{gO1}]], Hpm[{gI1}], Fv[{gI2}]], FFS, 1, 1}, 
  {VWLm, Fv, Cp[bar[UFe[{gO1}]], VWLm, Fv[{gI2}]], FFV, 1, 1}, 
  {VWRm, Fv, Cp[bar[UFe[{gO1}]], VWRm, Fv[{gI2}]], FFV, 1, 1}, 
  {bar[Fe], Hppmm, Cp[bar[UFe[{gO1}]], bar[Fe[{gI1}]], Hppmm[{gI2}]], FFS, 1, 
   1}}, {{Fv, Ah, Cp[UFv[{gO1}], Fv[{gI1}], Ah[{gI2}]], FFS, 1, 1/2}, 
  {conj[Hpm], Fe, Cp[UFv[{gO1}], conj[Hpm[{gI1}]], Fe[{gI2}]], FFS, 1, 1/2}, 
  {conj[VWLm], Fe, Cp[UFv[{gO1}], conj[VWLm], Fe[{gI2}]], FFV, 1, 1/2}, 
  {conj[VWRm], Fe, Cp[UFv[{gO1}], conj[VWRm], Fe[{gI2}]], FFV, 1, 1/2}, 
  {hh, Fv, Cp[UFv[{gO1}], hh[{gI1}], Fv[{gI2}]], FFS, 1, 1/2}, 
  {VP, Fv, Cp[UFv[{gO1}], VP, Fv[{gI2}]], FFV, 1, 1/2}, 
  {VZ, Fv, Cp[UFv[{gO1}], VZ, Fv[{gI2}]], FFV, 1, 1/2}, 
  {VZR, Fv, Cp[UFv[{gO1}], VZR, Fv[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fe], Hpm, Cp[UFv[{gO1}], bar[Fe[{gI1}]], Hpm[{gI2}]], FFS, 1, 1/2}, 
  {bar[Fe], VWLm, Cp[UFv[{gO1}], bar[Fe[{gI1}]], VWLm], FFV, 1, 1/2}, 
  {bar[Fe], VWRm, Cp[UFv[{gO1}], bar[Fe[{gI1}]], VWRm], FFV, 1, 1/2}}}
