{{{bar[Fd], Fd, Cp[VG, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 1/2, 1/2}, 
  {bar[Fu], Fu, Cp[VG, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 1/2, 1/2}, 
  {bar[gG], gG, Cp[VG, bar[gG], gG], GGV, 3, 1/2}, 
  {VG, VG, Cp[VG, VG, VG], VVV, 3, 1/4}, {VG, VG, Cp[VG, VG, VG, VG], VVVV, 
   1, 1/2}}, {{hh, Ah, Cp[VP, hh[{gI1}], Ah[{gI2}]], SSV, 1, 1/2}, 
  {bar[Fd], Fd, Cp[VP, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VP, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VP, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {Fv, Fv, Cp[VP, Fv[{gI1}], Fv[{gI2}]], FFV, 1, 1/4}, 
  {bar[gWLm], gWLm, Cp[VP, bar[gWLm], gWLm], GGV, 1, 1/2}, 
  {bar[gWRm], gWLm, Cp[VP, bar[gWRm], gWLm], GGV, 1, 1}, 
  {bar[gWLmC], gWLmC, Cp[VP, bar[gWLmC], gWLmC], GGV, 1, 1/2}, 
  {bar[gWRmC], gWLmC, Cp[VP, bar[gWRmC], gWLmC], GGV, 1, 1}, 
  {bar[gWRm], gWRm, Cp[VP, bar[gWRm], gWRm], GGV, 1, 1/2}, 
  {bar[gWRmC], gWRmC, Cp[VP, bar[gWRmC], gWRmC], GGV, 1, 1/2}, 
  {VZ, hh, Cp[VP, VZ, hh[{gI2}]], SVV, 1, 1/2}, 
  {VZR, hh, Cp[VP, VZR, hh[{gI2}]], SVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VP, conj[Hpm[{gI1}]], Hpm[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWLm], Hpm, Cp[VP, conj[VWLm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[VWRm], Hpm, Cp[VP, conj[VWRm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[VP, conj[Hppmm[{gI1}]], Hppmm[{gI2}]], SSV, 1, 
   1/2}, {conj[VWLm], VWLm, Cp[VP, conj[VWLm], VWLm], VVV, 1, 1/2}, 
  {conj[VWRm], VWLm, Cp[VP, conj[VWRm], VWLm], VVV, 1, 1}, 
  {conj[VWRm], VWRm, Cp[VP, conj[VWRm], VWRm], VVV, 1, 1/2}, 
  {Ah, Ah, Cp[VP, VP, Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VP, VP, hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VP, VP, conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[VP, VP, conj[Hppmm[{gI1}]], Hppmm[{gI1}]], SSVV, 1, 
   1}, {conj[VWLm], VWLm, Cp[VP, VP, conj[VWLm], VWLm], VVVV, 1, 1}, 
  {conj[VWRm], VWRm, Cp[VP, VP, conj[VWRm], VWRm], VVVV, 1, 1}}, 
 {{hh, Ah, Cp[VZ, hh[{gI1}], Ah[{gI2}]], SSV, 1, 1/2}, 
  {bar[Fd], Fd, Cp[VZ, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VZ, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VZ, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {Fv, Fv, Cp[VZ, Fv[{gI1}], Fv[{gI2}]], FFV, 1, 1/4}, 
  {bar[gWLm], gWLm, Cp[VZ, bar[gWLm], gWLm], GGV, 1, 1/2}, 
  {bar[gWRm], gWLm, Cp[VZ, bar[gWRm], gWLm], GGV, 1, 1}, 
  {bar[gWLmC], gWLmC, Cp[VZ, bar[gWLmC], gWLmC], GGV, 1, 1/2}, 
  {bar[gWRmC], gWLmC, Cp[VZ, bar[gWRmC], gWLmC], GGV, 1, 1}, 
  {bar[gWRm], gWRm, Cp[VZ, bar[gWRm], gWRm], GGV, 1, 1/2}, 
  {bar[gWRmC], gWRmC, Cp[VZ, bar[gWRmC], gWRmC], GGV, 1, 1/2}, 
  {VP, hh, Cp[VZ, VP, hh[{gI2}]], SVV, 1, 1/2}, 
  {VZ, hh, Cp[VZ, VZ, hh[{gI2}]], SVV, 1, 1/2}, 
  {VZR, hh, Cp[VZ, VZR, hh[{gI2}]], SVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VZ, conj[Hpm[{gI1}]], Hpm[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWLm], Hpm, Cp[VZ, conj[VWLm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[VWRm], Hpm, Cp[VZ, conj[VWRm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[VZ, conj[Hppmm[{gI1}]], Hppmm[{gI2}]], SSV, 1, 
   1/2}, {conj[VWLm], VWLm, Cp[VZ, conj[VWLm], VWLm], VVV, 1, 1/2}, 
  {conj[VWRm], VWLm, Cp[VZ, conj[VWRm], VWLm], VVV, 1, 1}, 
  {conj[VWRm], VWRm, Cp[VZ, conj[VWRm], VWRm], VVV, 1, 1/2}, 
  {Ah, Ah, Cp[VZ, VZ, Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VZ, VZ, hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VZ, VZ, conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[VZ, VZ, conj[Hppmm[{gI1}]], Hppmm[{gI1}]], SSVV, 1, 
   1}, {conj[VWLm], VWLm, Cp[VZ, VZ, conj[VWLm], VWLm], VVVV, 1, 1}, 
  {conj[VWRm], VWRm, Cp[VZ, VZ, conj[VWRm], VWRm], VVVV, 1, 1}}, 
 {{hh, Ah, Cp[VZR, hh[{gI1}], Ah[{gI2}]], SSV, 1, 1/2}, 
  {bar[Fd], Fd, Cp[VZR, bar[Fd[{gI1}]], Fd[{gI2}]], FFV, 3, 1/2}, 
  {bar[Fe], Fe, Cp[VZR, bar[Fe[{gI1}]], Fe[{gI2}]], FFV, 1, 1/2}, 
  {bar[Fu], Fu, Cp[VZR, bar[Fu[{gI1}]], Fu[{gI2}]], FFV, 3, 1/2}, 
  {Fv, Fv, Cp[VZR, Fv[{gI1}], Fv[{gI2}]], FFV, 1, 1/4}, 
  {bar[gWLm], gWLm, Cp[VZR, bar[gWLm], gWLm], GGV, 1, 1/2}, 
  {bar[gWRm], gWLm, Cp[VZR, bar[gWRm], gWLm], GGV, 1, 1}, 
  {bar[gWLmC], gWLmC, Cp[VZR, bar[gWLmC], gWLmC], GGV, 1, 1/2}, 
  {bar[gWRmC], gWLmC, Cp[VZR, bar[gWRmC], gWLmC], GGV, 1, 1}, 
  {bar[gWRm], gWRm, Cp[VZR, bar[gWRm], gWRm], GGV, 1, 1/2}, 
  {bar[gWRmC], gWRmC, Cp[VZR, bar[gWRmC], gWRmC], GGV, 1, 1/2}, 
  {VP, hh, Cp[VZR, VP, hh[{gI2}]], SVV, 1, 1/2}, 
  {VZ, hh, Cp[VZR, VZ, hh[{gI2}]], SVV, 1, 1/2}, 
  {VZR, hh, Cp[VZR, VZR, hh[{gI2}]], SVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VZR, conj[Hpm[{gI1}]], Hpm[{gI2}]], SSV, 1, 1/2}, 
  {conj[VWLm], Hpm, Cp[VZR, conj[VWLm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[VWRm], Hpm, Cp[VZR, conj[VWRm], Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[VZR, conj[Hppmm[{gI1}]], Hppmm[{gI2}]], SSV, 1, 
   1/2}, {conj[VWLm], VWLm, Cp[VZR, conj[VWLm], VWLm], VVV, 1, 1/2}, 
  {conj[VWRm], VWLm, Cp[VZR, conj[VWRm], VWLm], VVV, 1, 1}, 
  {conj[VWRm], VWRm, Cp[VZR, conj[VWRm], VWRm], VVV, 1, 1/2}, 
  {Ah, Ah, Cp[VZR, VZR, Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VZR, VZR, hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VZR, VZR, conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 1, 1}, 
  {conj[Hppmm], Hppmm, Cp[VZR, VZR, conj[Hppmm[{gI1}]], Hppmm[{gI1}]], SSVV, 
   1, 1}, {conj[VWLm], VWLm, Cp[VZR, VZR, conj[VWLm], VWLm], VVVV, 1, 1}, 
  {conj[VWRm], VWRm, Cp[VZR, VZR, conj[VWRm], VWRm], VVVV, 1, 1}}, 
 {{Hpm, Ah, Cp[conj[VWLm], Hpm[{gI1}], Ah[{gI2}]], SSV, 1, 1}, 
  {VWRm, Ah, Cp[conj[VWLm], VWRm, Ah[{gI2}]], SVV, 1, 1}, 
  {bar[Fu], Fd, Cp[conj[VWLm], bar[Fu[{gI1}]], Fd[{gI2}]], FFV, 3, 1}, 
  {Fv, Fe, Cp[conj[VWLm], Fv[{gI1}], Fe[{gI2}]], FFV, 1, 1}, 
  {bar[gWLmC], gP, Cp[conj[VWLm], bar[gWLmC], gP], GGV, 1, 1}, 
  {bar[gWRmC], gP, Cp[conj[VWLm], bar[gWRmC], gP], GGV, 1, 1}, 
  {bar[gP], gWLm, Cp[conj[VWLm], bar[gP], gWLm], GGV, 1, 1}, 
  {bar[gZ], gWLm, Cp[conj[VWLm], bar[gZ], gWLm], GGV, 1, 1}, 
  {bar[gZR], gWLm, Cp[conj[VWLm], bar[gZR], gWLm], GGV, 1, 1}, 
  {bar[gP], gWRm, Cp[conj[VWLm], bar[gP], gWRm], GGV, 1, 1}, 
  {bar[gZ], gWRm, Cp[conj[VWLm], bar[gZ], gWRm], GGV, 1, 1}, 
  {bar[gZR], gWRm, Cp[conj[VWLm], bar[gZR], gWRm], GGV, 1, 1}, 
  {bar[gWLmC], gZ, Cp[conj[VWLm], bar[gWLmC], gZ], GGV, 1, 1}, 
  {bar[gWRmC], gZ, Cp[conj[VWLm], bar[gWRmC], gZ], GGV, 1, 1}, 
  {bar[gWLmC], gZR, Cp[conj[VWLm], bar[gWLmC], gZR], GGV, 1, 1}, 
  {bar[gWRmC], gZR, Cp[conj[VWLm], bar[gWRmC], gZR], GGV, 1, 1}, 
  {Hpm, hh, Cp[conj[VWLm], Hpm[{gI1}], hh[{gI2}]], SSV, 1, 1}, 
  {VWLm, hh, Cp[conj[VWLm], VWLm, hh[{gI2}]], SVV, 1, 1}, 
  {VWRm, hh, Cp[conj[VWLm], VWRm, hh[{gI2}]], SVV, 1, 1}, 
  {VP, Hpm, Cp[conj[VWLm], VP, Hpm[{gI2}]], SVV, 1, 1}, 
  {VZ, Hpm, Cp[conj[VWLm], VZ, Hpm[{gI2}]], SVV, 1, 1}, 
  {VZR, Hpm, Cp[conj[VWLm], VZR, Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Hpm], Hppmm, Cp[conj[VWLm], conj[Hpm[{gI1}]], Hppmm[{gI2}]], SSV, 1, 
   1}, {conj[VWLm], Hppmm, Cp[conj[VWLm], conj[VWLm], Hppmm[{gI2}]], SVV, 1, 
   1}, {conj[VWRm], Hppmm, Cp[conj[VWLm], conj[VWRm], Hppmm[{gI2}]], SVV, 1, 
   1}, {VWLm, VP, Cp[conj[VWLm], VWLm, VP], VVV, 1, 1}, 
  {VWRm, VP, Cp[conj[VWLm], VWRm, VP], VVV, 1, 1}, 
  {VZ, VWLm, Cp[conj[VWLm], VZ, VWLm], VVV, 1, 1}, 
  {VZR, VWLm, Cp[conj[VWLm], VZR, VWLm], VVV, 1, 1}, 
  {VZ, VWRm, Cp[conj[VWLm], VZ, VWRm], VVV, 1, 1}, 
  {VZR, VWRm, Cp[conj[VWLm], VZR, VWRm], VVV, 1, 1}, 
  {Ah, Ah, Cp[VWLm, conj[VWLm], Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VWLm, conj[VWLm], hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VWLm, conj[VWLm], conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 
   1, 1}, {conj[Hppmm], Hppmm, Cp[VWLm, conj[VWLm], conj[Hppmm[{gI1}]], 
    Hppmm[{gI1}]], SSVV, 1, 1}, {VP, VP, Cp[VWLm, conj[VWLm], VP, VP], VVVV, 
   1, 1/2}, {conj[VWLm], VWLm, Cp[VWLm, conj[VWLm], conj[VWLm], VWLm], VVVV, 
   1, 1}, {conj[VWRm], VWRm, Cp[VWLm, conj[VWLm], conj[VWRm], VWRm], VVVV, 1, 
   1}, {VZ, VZ, Cp[VWLm, conj[VWLm], VZ, VZ], VVVV, 1, 1/2}, 
  {VZR, VZR, Cp[VWLm, conj[VWLm], VZR, VZR], VVVV, 1, 1/2}}, 
 {{Hpm, Ah, Cp[conj[VWRm], Hpm[{gI1}], Ah[{gI2}]], SSV, 1, 1}, 
  {VWLm, Ah, Cp[conj[VWRm], VWLm, Ah[{gI2}]], SVV, 1, 1}, 
  {bar[Fu], Fd, Cp[conj[VWRm], bar[Fu[{gI1}]], Fd[{gI2}]], FFV, 3, 1}, 
  {Fv, Fe, Cp[conj[VWRm], Fv[{gI1}], Fe[{gI2}]], FFV, 1, 1}, 
  {bar[gWLmC], gP, Cp[conj[VWRm], bar[gWLmC], gP], GGV, 1, 1}, 
  {bar[gWRmC], gP, Cp[conj[VWRm], bar[gWRmC], gP], GGV, 1, 1}, 
  {bar[gP], gWLm, Cp[conj[VWRm], bar[gP], gWLm], GGV, 1, 1}, 
  {bar[gZ], gWLm, Cp[conj[VWRm], bar[gZ], gWLm], GGV, 1, 1}, 
  {bar[gZR], gWLm, Cp[conj[VWRm], bar[gZR], gWLm], GGV, 1, 1}, 
  {bar[gP], gWRm, Cp[conj[VWRm], bar[gP], gWRm], GGV, 1, 1}, 
  {bar[gZ], gWRm, Cp[conj[VWRm], bar[gZ], gWRm], GGV, 1, 1}, 
  {bar[gZR], gWRm, Cp[conj[VWRm], bar[gZR], gWRm], GGV, 1, 1}, 
  {bar[gWLmC], gZ, Cp[conj[VWRm], bar[gWLmC], gZ], GGV, 1, 1}, 
  {bar[gWRmC], gZ, Cp[conj[VWRm], bar[gWRmC], gZ], GGV, 1, 1}, 
  {bar[gWLmC], gZR, Cp[conj[VWRm], bar[gWLmC], gZR], GGV, 1, 1}, 
  {bar[gWRmC], gZR, Cp[conj[VWRm], bar[gWRmC], gZR], GGV, 1, 1}, 
  {Hpm, hh, Cp[conj[VWRm], Hpm[{gI1}], hh[{gI2}]], SSV, 1, 1}, 
  {VWLm, hh, Cp[conj[VWRm], VWLm, hh[{gI2}]], SVV, 1, 1}, 
  {VWRm, hh, Cp[conj[VWRm], VWRm, hh[{gI2}]], SVV, 1, 1}, 
  {VP, Hpm, Cp[conj[VWRm], VP, Hpm[{gI2}]], SVV, 1, 1}, 
  {VZ, Hpm, Cp[conj[VWRm], VZ, Hpm[{gI2}]], SVV, 1, 1}, 
  {VZR, Hpm, Cp[conj[VWRm], VZR, Hpm[{gI2}]], SVV, 1, 1}, 
  {conj[Hpm], Hppmm, Cp[conj[VWRm], conj[Hpm[{gI1}]], Hppmm[{gI2}]], SSV, 1, 
   1}, {conj[VWLm], Hppmm, Cp[conj[VWRm], conj[VWLm], Hppmm[{gI2}]], SVV, 1, 
   1}, {conj[VWRm], Hppmm, Cp[conj[VWRm], conj[VWRm], Hppmm[{gI2}]], SVV, 1, 
   1}, {VWLm, VP, Cp[conj[VWRm], VWLm, VP], VVV, 1, 1}, 
  {VWRm, VP, Cp[conj[VWRm], VWRm, VP], VVV, 1, 1}, 
  {VZ, VWLm, Cp[conj[VWRm], VZ, VWLm], VVV, 1, 1}, 
  {VZR, VWLm, Cp[conj[VWRm], VZR, VWLm], VVV, 1, 1}, 
  {VZ, VWRm, Cp[conj[VWRm], VZ, VWRm], VVV, 1, 1}, 
  {VZR, VWRm, Cp[conj[VWRm], VZR, VWRm], VVV, 1, 1}, 
  {Ah, Ah, Cp[VWRm, conj[VWRm], Ah[{gI1}], Ah[{gI1}]], SSVV, 1, 1/2}, 
  {hh, hh, Cp[VWRm, conj[VWRm], hh[{gI1}], hh[{gI1}]], SSVV, 1, 1/2}, 
  {conj[Hpm], Hpm, Cp[VWRm, conj[VWRm], conj[Hpm[{gI1}]], Hpm[{gI1}]], SSVV, 
   1, 1}, {conj[Hppmm], Hppmm, Cp[VWRm, conj[VWRm], conj[Hppmm[{gI1}]], 
    Hppmm[{gI1}]], SSVV, 1, 1}, {VP, VP, Cp[VWRm, conj[VWRm], VP, VP], VVVV, 
   1, 1/2}, {conj[VWLm], VWLm, Cp[VWRm, conj[VWRm], conj[VWLm], VWLm], VVVV, 
   1, 1}, {conj[VWRm], VWRm, Cp[VWRm, conj[VWRm], conj[VWRm], VWRm], VVVV, 1, 
   1}, {VZ, VZ, Cp[VWRm, conj[VWRm], VZ, VZ], VVVV, 1, 1/2}, 
  {VZR, VZR, Cp[VWRm, conj[VWRm], VZR, VZR], VVVV, 1, 1/2}}}
