{{{Ah, Ah, Cp[Uhh[{gO1}], Ah[{gI1}], Ah[{gI2}]], SSS, 1, 1/4}, 
  {bar[Fd], Fd, Cp[Uhh[{gO1}], bar[Fd[{gI1}]], Fd[{gI2}]], FFS, 3, 1/2}, 
  {bar[Fe], Fe, Cp[Uhh[{gO1}], bar[Fe[{gI1}]], Fe[{gI2}]], FFS, 1, 1/2}, 
  {bar[Fu], Fu, Cp[Uhh[{gO1}], bar[Fu[{gI1}]], Fu[{gI2}]], FFS, 3, 1/2}, 
  {Fv, Fv, Cp[Uhh[{gO1}], Fv[{gI1}], Fv[{gI2}]], FFS, 1, 1/4}, 
  {bar[gWLm], gWLm, Cp[Uhh[{gO1}], bar[gWLm], gWLm], GGS, 1, 1/2}, 
  {bar[gWLmC], gWLmC, Cp[Uhh[{gO1}], bar[gWLmC], gWLmC], GGS, 1, 1/2}, 
  {bar[gWRm], gWRm, Cp[Uhh[{gO1}], bar[gWRm], gWRm], GGS, 1, 1/2}, 
  {bar[gWRmC], gWRmC, Cp[Uhh[{gO1}], bar[gWRmC], gWRmC], GGS, 1, 1/2}, 
  {bar[gZ], gZ, Cp[Uhh[{gO1}], bar[gZ], gZ], GGS, 1, 1/2}, 
  {bar[gZR], gZR, Cp[Uhh[{gO1}], bar[gZR], gZR], GGS, 1, 1/2}, 
  {hh, hh, Cp[Uhh[{gO1}], hh[{gI1}], hh[{gI2}]], SSS, 1, 1/4}, 
  {conj[Hpm], Hpm, Cp[Uhh[{gO1}], conj[Hpm[{gI1}]], Hpm[{gI2}]], SSS, 1, 
   1/2}, {conj[Hppmm], Hppmm, Cp[Uhh[{gO1}], conj[Hppmm[{gI1}]], 
    Hppmm[{gI2}]], SSS, 1, 1/2}, {conj[VWLm], VWLm, 
   Cp[Uhh[{gO1}], conj[VWLm], VWLm], SVV, 1, 1/2}, 
  {conj[VWRm], VWRm, Cp[Uhh[{gO1}], conj[VWRm], VWRm], SVV, 1, 1/2}, 
  {VZ, VZ, Cp[Uhh[{gO1}], VZ, VZ], SVV, 1, 1/4}, 
  {VZR, VZR, Cp[Uhh[{gO1}], VZR, VZR], SVV, 1, 1/4}}}
